<?php
/* $Id$ */

//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
require_once("f_runmode.phtml");
$mode = "";

require("f_bevalidboardingpass.phtml");
require("f_kickoff.phtml");
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_zipdump.phtml");
//
if (ConnectSelectDbInstanceUNPUBLISHED($db_link) == "TRUE")
  {
  if (BeValidBoardingPass($db_link,$bpn,$mode) == "")
    {
    KickOff($mode);
    }
  else
    {
    ZipDump($db_link,$whole_query,$bpn,$filename);
    }
  }
?>