<?php
/* $Id$ */

//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }

require("f_bevalidboardingpass.phtml");
require("f_kickoff.phtml");
require_once("f_zipdump.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
//
  if (BeValidBoardingPass($db_link,$bpn,$mode) == "")
    {
    KickOff($mode);
    }
  else
    {
    ZipDump($db_link,$whole_query,$bpn,$filename);
    }
?>