<?
//
// $Id: f_bevalidboardingpass.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
function BeValidBoardingPass
   (
   $db_link,
   $bpn
   )
   {
   $saved_error_level = error_reporting(E_ALL);

   $bpn = kix\k::Safe($bpn,kix\k::PhpValueOf_safe_hint_type("HEX"));

   global $REMOTE_ADDR;

   //
   // Init vars that are will be implicitly set by extract() so PHP won't issue undefined var warnings while error reporting is
   // at E_ALL.
   //
   $debug = $agency = $ip = $expiration_time = "";
   //
   // Check for production debug mode.
   //
   extract(  //Sets $debug.
      mysqli_fetch_array(
         $db_link->query("select value as debug from tuning_parm where name='debug-boarding-pass'")));
   //
   // Now see if the specified boarding pass is valid.
   //
   $result = $db_link->query
      (
      "select agency,ip,expiration_time from manifest "
      .  "   where bpn='$bpn' "
      )
      or die("BeValidBoardingPass query failed with error:  " . mysqli_error($db_link));
   //
   if (mysqli_num_rows($result))
      {
      extract(mysqli_fetch_array($result));  // to get $agency value to return to this function's caller
         //
         // Also sets $ip and $expiration_time.
         //
//
// Skip the IP test for now since some AOL users have reported mismatches within a single session.
//
//    if ($ip == $REMOTE_ADDR)
//       {
         if ($expiration_time >= time())
            {
            //
            // Get time-bump value from tuning parm table.
            //
            extract(  //Sets $bump_factor
               mysqli_fetch_array(
                  $db_link->query(
                     "select value as bump_factor from tuning_parm where name='boarding-pass-valid-minutes'")));
            //
            // Extend expiration date
            //
            $result = $db_link->query
               (
               "update manifest "
               .  " set expiration_time = expiration_time + " . $bump_factor*60
               .  " where bpn='$bpn' "
               .  "    and ip='$ip' "
               .  "    and agency='$agency' "
               );
            }
         else
            {
            if ($debug) echo "<p><b>!Boarding pass expired " . (time() - $expiration_time) . " seconds ago!</b></p>\n";
            $agency = "";
            }
//       }
//    else
//       {
//       if ($debug) echo "<p><b>!IP address mismatch: current=$REMOTE_ADDR, manifest=$ip!</b></p>\n";
//       $agency = "";
//       }
      }
   else
      {
      if ($debug) echo "<p><b>!No such boarding pass number found in manifest!</b></p>\n";
      $agency = "";
      }
   //
   // Remove all expired records.
   //
   $result = $db_link->query("delete from manifest where expiration_time < " . time())
      or die("Removal of expired boarding passes failed with error: " . mysqli_error($db_link));
   //
   error_reporting($saved_error_level);
   return ($agency);
   }
?>