<?
//
// $Id: f_beauthorized.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
function BeAuthorized
   (
   $db_link,
   $email_addr,
   $agency
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $found_email_addr = "";
   //
   $result = $db_link->query
      (
      "select email_addr as found_email_addr from user "
      .  "   where email_addr='" . kix\k::Safe($email_addr,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS")) . "'"
      .  "      and agency='" . kix\k::Safe($agency,kix\k::PhpValueOf_safe_hint_type("ALPHA")) . "' "
      )
      or die("BeAuthorized query failed with error:  " . mysqli_error($db_link));
   //
   if (mysqli_num_rows($result)) extract(mysqli_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return ($found_email_addr != "");
   }
?>