<?
//
// $Id: f_emailaddrofbpn.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
function EmailAddrOfBpn
   (
   $db_link,
   $bpn
   )
   {
   $saved_error_level = error_reporting(E_ALL);

   //
   // Init vars that are will be implicitly set by extract() so PHP won't issue undefined var warnings while error reporting is
   // at E_ALL.
   //
   $email_addr = "";
   //
   // Now see if the specified boarding pass is valid.
   //
   $result = $db_link->query("select email_addr from manifest where bpn='" . kix\k::Safe($bpn,kix\k::PhpValueOf_safe_hint_type("HEX")) . "'")
      or die("BeValidBoardingPass query failed with error:  " . mysqli_error($db_link));
   //
   if (mysqli_num_rows($result))
      {
      extract(mysqli_fetch_array($result));
      }
   else
      {
      echo FormattedNoteAppendage("SEVERE","NOSUCHBPN","No such BPN found in manifest.");
      }
   //
   error_reporting($saved_error_level);
   return ($email_addr);
   }
?>