<?
//
// $Id: f_formattednoteappendage.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
function FormattedNoteAppendage
   (
   $condition,
   $mnemonic,
   $message,
   $source = "KEYCLICK"
   )
   {
   $pad_mask = "................";
   $num_invisible_chars = 0;
   //
   $condition = strtoupper($condition);
   switch ($condition)
      {
      case "WARNING":
      case "ERROR":
      case "SEVERE":
      case "FATAL":
         $condition = "<b>$condition</b>";
         $num_invisible_chars = 7;
      }
   //
   $s =  "<br>:<br>"
      .  "<tt>"
      .  str_pad("mesg(" . strtoupper($mnemonic) . ")",16,$pad_mask)
      .  "from(" .  strtoupper($source) .  ")"
      .  "<br>"
      .  str_pad("type($condition)",(16 + $num_invisible_chars),$pad_mask)
      .  "time(" .  date("Y-m-d-H:i-T") . ")"
      .  "</tt>"
      .  "<br>"
      .  addslashes($message);
   return $s;
   }
?>