<?
//
// $Id: f_kickoff.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
function KickOff()
   {
   ?>
   <p>Your KEYclick Boarding Pass is invalid.&nbsp; Possible reasons include:</p>
   <ul>
      <li><p>Your KEYclick session has been idle for more than 30 minutes;</p></li>
      <li><p>Your IP address has changed.&nbsp This can happen when you hang up and redial a dial-up Internet connection,
         or when you move to a different computer.</p></li>
   </ul>
   <p><b><a href="javascript:close();">Click here to log back into KEYclick.</a></b></p>
   <?
   }
?>