<?
//
// $Id: f_methodselectionlist.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
function MethodSelectionList
   (
   $db_link,
   $agency,
   $selected_option = ""
   )
//
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $result = @$db_link->query("select * from method order by cardinality");
   //
   if (!mysqli_error($db_link) && mysqli_num_rows($result))
      {
      echo "<select name=method>\n";
      //
      if ($selected_option == "")
         {
         //
         // First time is a special case.  If the cardinality of the first row is 0 (zero), then the row should be selected by
         // default.  If not, nothing should be selected by default.
         //
         extract(mysqli_fetch_array($result));
         if ($cardinality != 0)
            {
            echo "   <option value=\"\">&nbsp;</option>\n";
            }
         echo "   <option value=\"$enumeral\">$description</option>\n";
         }
      //
      while($row = mysqli_fetch_array($result))
         {
         $enumeral = $description = $cardinality = "";
         extract($row);
         echo "   <option value=\"$enumeral\"";
         if ($enumeral == $selected_option) echo " selected";
         echo ">$description</option>\n";
         }
      //
      echo "</select>\n";
      }
   else
      {
      echo "(Not configured)\n";
      }
   //
   error_reporting($saved_error_level);
   }
?>