<?
//
// $Id: f_readdump-popnamcnt.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
function ReadDump_POPNAMCNT
   (
   $db_link,
   $agency
   )
{
extract(  // Sets $chunk_size.
   mysqli_fetch_array(
      $db_link->query("select value as chunk_size from tuning_parm where name='popnamcnt-chunk-size'")));
//
$statement_array = array();
$statement_array[$i = 0] = "drop table if exists name";
$statement_array[++$i] = "CREATE TABLE name select name from resident_base where name is not null and agency = '" . kix\k::Safe($agency,kix\k::PhpValueOf_safe_hint_type("ALPHA")) . "'";
$statement_array[++$i] = "drop table if exists name_count";
$statement_array[++$i] = "create table name_count "
   . "select name,count(*) as occurrences from name group by name limit 0,$chunk_size";
//
$num_statements = count($statement_array);
//
// Execute each statement in the statement array.
//
for ($i = 0; $i < $num_statements; $i++)
   {
   $db_link->query($statement_array[$i]) or die("Query [$statement_array[$i]] failed with error: " . mysqli_error($db_link));
   }
//
// Figure out how many rows are in the intermediate table.
//
$result = $db_link->query("select count(*) as num_name_rows from name")
   or die("Count failed with error: " . mysqli_error($db_link));
extract(mysqli_fetch_array($result));  // Sets $num_name_rows.
//
// Repeatedly reduce the size of the problem by removing rows from the intermediate table that have already been
// transferred to the target table.  Then transfer some more.
//
for ($i = 0; $i < $num_name_rows; $i += $chunk_size)
   {
   $result = $db_link->query("select name from name_count limit $i,$chunk_size")
      or die("Selection of quasi-keys newly-inserted into target table failed with error: " . mysqli_error($db_link));
   $quasi_key_list = "";
   while ($row = mysqli_fetch_array($result))
      {
      extract($row);  // Sets $name.
      $name = addslashes($name);
      $quasi_key_list .= "'$name',";
      }
   $quasi_key_list .= "'$name'";  // Logically unnecessary, but a cheap cheat to make the string syntactically correct.
   //
   $db_link->query("delete from name where name in ($quasi_key_list)")
      or die("Scattered delete failed with error: " . mysqli_error($db_link) . " quasi_key_list=$quasi_key_list");
   //
   $db_link->query
      (
      "insert into name_count "
      . "select name, count(*) as occurrences from name "
      . "group by name limit $chunk_size"
      )
      or die("Grouped insert failed at virtual offset " . ($i + $chunk_size) . " with error: " . mysqli_error($db_link));
   }
$db_link->query("drop table name") or die("Drop of name table failed with error: " . mysqli_error($db_link));
$db_link->query("delete from name_count where occurrences = 1")
   or die("Delete of singlets failed with error: " . mysqli_error($db_link));
}
?>