<?
//
// $Id: f_readdump-rodfolup0.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $ */
//
function ReadDump_RODFOLUP0
   (
   $db_link,
   $year_num,
   $month_num,
   $day_num,
   $agency
   )
{
$statement_array = array();
$statement_array[$i = 0] = "drop table if exists recent_donation";
$statement_array[++$i] = "drop table if exists resident_follow_up";
$statement_array[++$i] = "CREATE TABLE recent_donation"
. " SELECT id"
.   " FROM donation"
.   " WHERE date > '" . kix\k::Safe($year_num,kix\k::PhpValueOf_safe_hint_type("NUM")) . "-" . kix\k::Safe($month_num,kix\k::PhpValueOf_safe_hint_type("NUM")) . "-" . kix\k::Safe($day_num,kix\k::PhpValueOf_safe_hint_type("NUM")) . "'";
$statement_array[++$i] = "CREATE TABLE resident_follow_up"
. " SELECT resident_base.id"
  . " , resident_base.name"
  . " , concat(house_num,' ',street.name) as address1"
  . " , city.name as city"
  . " , state.abbreviation as state"
. " FROM resident_base"
  . " join street on (street.id=resident_base.street_id)"
  . " join city on (city.id=street.city_id)"
  . " join state on (state.id=city.state_id)"
  . " LEFT JOIN recent_donation on (recent_donation.id=resident_base.id)"
. " WHERE recent_donation.id IS NULL"
  . " and agency='" . kix\k::Safe($agency,kix\k::PhpValueOf_safe_hint_type("ALPHA")) . "'";
$statement_array[++$i] = "drop table recent_donation";
//
$num_statements = count($statement_array);
//
// Execute each statement in the statement array.
//
for ($i = 0; $i < $num_statements; $i++)
   {
   $db_link->query($statement_array[$i]) or die("Query [$statement_array[$i]] failed with error: " . mysqli_error($db_link));
   }
}
?>