<?
//
// $Id: f_readdump.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $ */
//
function ReadDump
  (
  $db_link,
  $sql_query,
  $bpn,
  $allow_dynamic_sorting = '1',
  $be_viewable_result = "TRUE",
  $be_drill_down_available = 'TRUE',
  $table_border = 0,
  $cell_padding = 3,
  $max_text_field_display_len = 64,
  $is_js_confirmed = "0",
  $lang = "en",
  $server = "1",
  $pos = "0",
  $goto = "form-analyze.phtml",
  $zero_rows = "None found.",
  $prev_sql_query = ""
  )
  {
  require_once('f_viewquery.phtml');
  ViewQuery
    (
    $db_link,
    $bpn,
    $sql_query,
    $lang,
    $server,
    $zero_rows,
    ("" . $goto),
    $table_border,
    $cell_padding,
    $max_text_field_display_len,
    ($be_drill_down_available == 'TRUE' ? 'urnn00000' : 'nnnn00000') // for row_action_designator -- send 'nnnn00000' to preserve header/data column alignment if no drill-down will be available
    );
  }
?>
