<?
//
// $Id: f_roleemailaddress.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
function RoleEmailAddress
   (
   $db_link,
   $role = "",
   $agency = ""
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $email_addr = "";
   $role = (($role == "") ? "sysadmin" : kix\k::Safe($role,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_ALPHA")));
   //
   $result = $db_link->query
      (
      "select email_addr"
      . " from authority"
      . " where role='$role'"
      .   " and agency='" . kix\k::Safe($agency,kix\k::PhpValueOf_safe_hint_type("ALPHA")) . "'"
      . " limit 1"
      )
      or die("RoleEmailAddress query failed with error:  " . mysqli_error($db_link));
   //
   if (mysqli_num_rows($result)) extract(mysqli_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return $email_addr;
   }
?>