<?
//
// $Id: f_methodselectionlist.phtml 755 2002-11-02 21:47:27Z kevinanlipscomb $
//
function StreetSelectionList
   (
   $db_link,
   $mode = "",
   $selected_option = ""
   )
//
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $result = @$db_link->query
      (
      "select street.id"
      . " , concat(street.name,', ',city.name,', ',state.abbreviation) as spec"
      . " from " . $mode . "street"
      .   " join " . $mode . "city on (city.id=street.city_id)"
      .   " join " . $mode . "state on (state.id=city.state_id)"
      . " order by state.abbreviation,city.name,street.name"
      );
   //
   if (!mysqli_error($db_link) && mysqli_num_rows($result))
      {
      echo "<select name=street_id>\n";
      //
      if ($selected_option == "")
        {
        echo "   <option value=\"\">-- Select --</option>\n";
        }
      while($row = mysqli_fetch_array($result))
         {
         $id = $spec = "";
         extract($row);
         echo "   <option value=\"$id\"";
         if ($id == $selected_option) echo " selected";
         echo ">$spec</option>\n";
         }
      //
      echo "</select>\n";
      }
   //
   error_reporting($saved_error_level);
   }
?>