<?php
//
// $Id: f_viewquery.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
function ViewQuery
  (
  $db_link,
  $bpn,
  $sql_query,
  $lang,
  $server,
  $zero_rows,
  $goto,
  $table_border,
  $cell_padding,
  $max_text_field_display_len,
  $disp_mode = ""
  )
  {
  $result = $db_link->query($sql_query) or die("Query $sql_query returned '" . mysqli_error($db_link) . "'");
  if(($num_rows = @mysqli_num_rows($result)) < 1)
    {
    echo "<p>$zero_rows</p>";
    }
  else
    {
    $fields_meta = mysqli_fetch_fields($result);
    PMA_displayTable
      (
      $result,
      $disp_mode, // see the "PMA_setDisplayMode()" function in libraries/display_tbl.lib.php3
      $fields_meta,
      count($fields_meta),
      $bpn,
      $max_text_field_display_len,
      "",
      $table_border,
      $cell_padding
      );
    }
  mysqli_free_result($result);
  }
?>