<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_password.phtml");
require_once("f_connectselectdb.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
?>
<html>

<head><title>KEYclick - Analyses & Reports</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced("eye-candy",1); ?>
        </td><td>
           <h6 align="center">
              <a href="<? echo HomePageUrl(); ?>">KEYCLICK SYSTEM</a></h6>
           <h1 align="center">Analyses & Reports</h1>
        </td></tr></table>
        <hr>
        <br>
        <?
        if (ConnectSelectDb("localhost","kalipso",Password(),"keyclick") != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>KEYclick's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
           </blockquote>            
           </b>
           <?
           }
        else
           {
           //
           $agency = BeValidBoardingPass($bpn,$mode);
           if ($agency == "")
              {
              KickOff($mode);
              }
           else
              {
              echo "<p>The following analyses have been configured for your agency.&nbsp; For other analyses, contact "
                 . "the <a href=mailto:\"" . RoleEmailAddress("",$mode) . "\">KEYclick System Administrator</a>.</p><br>\n"
                 . "<table align=center width=80%>\n";
              //
              $result = mysql_query
                 (
                 "select short_description "
                 . "   , enumeral "
                 . "   , long_description "
                 . "   , sql "
                 . "from " . $mode . "analysis "
                 . "where agency='$agency' "
                 . "order by position "
                 )
                 or die("Retrieval of analyses failed with error: " . mysql_error());
              //
              if (!mysql_num_rows($result))
                 {
                 echo "<tr><td><p>None</p></td></tr>";
                 }
              else
                 {
                 while ($row = mysql_fetch_array($result))
                    {
                    $short_description = $long_description = $sql = "";
                    extract($row);
                    echo "   <tr>\n"
                       . "      <td><b>$short_description</b></td>\n"
                       . "      <td align=right>\n"
                       . "         <form action=" . $mode . "analyze.phtml method=post>\n"
                       . "            <input type=hidden name=bpn value=$bpn>\n"
                       . "            <input type=hidden name=filename value=$enumeral>\n"
                       . "            <input type=hidden name=sql_query value=\"$sql\">\n"
                       . "            <input type=radio name=format value=html checked>View on screen\n"
                       . "               &nbsp;&nbsp;&nbsp;\n"
                       . "            <input type=radio name=format value=zip>Download as ZIP file\n"
                       . "               &nbsp;&nbsp;&nbsp;\n"
                       . "            <input type=submit value=\"Go!\">\n"
                       . "         </form>\n"
                       . "      </td>\n"
                       . "   </tr>\n"
                       . "   <tr>\n"
                       . "      <td colspan=2><blockquote><i>$long_description</i></blockquote><hr></td>\n"
                       . "   </tr>\n";
                    }
                 }
              echo "</table>\n";
              }
           }
        ?>
        <br>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
      </td>
    </tr>
  </table>
</body>

</html>
