<?
//
// $Id: form-analyze.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
if (isset($parent_enumeral_expression)) $parent_enumeral_expression = kix\k::Safe($parent_enumeral_expression,kix\k::PhpValueOf_safe_hint_type("PUNCTUATED"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head><title>KEYclick - Analyses & Reports</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"eye-candy",1); ?>
        </td><td>
           <h6 align="center">
              <a href="javascript:close();">KEYCLICK SYSTEM</a></h6>
           <h1 align="center">Analyses & Reports</h1>
        </td></tr></table>
        <hr>
        <br>
        <?
           $agency = BeValidBoardingPass($db_link,$bpn);
           if ($agency == "")
              {
              KickOff();
              }
           else
              {
              echo "<p>The following analyses are available in this context.&nbsp; For other analyses, contact "
                 . "the <a href=mailto:\"" . RoleEmailAddress($db_link) . "\">KEYclick System Administrator</a>.</p><br>\n"
                 . "<table align=center width=90%>\n";
              //
              extract(  // Sets $chunk_size.
                 mysqli_fetch_array(
                    $db_link->query(
                       "select value as chunk_size from tuning_parm where name='screen-view-chunk-size'")));
              //
              switch ($parent_enumeral_expression)
              {
              case null:
              case "":
                 {
                 //
                 // We must be at the top contextual level.  First, there are no "parent" analyses at this level.  Second,
                 // this is the level where we want to present the analyses that must be maintained programmatically (ie,
                 // in PHP, as opposed to those that can be maintained as records in the analyses table).  Some analyses
                 // must be maintained programatically because of sheer complexity or because of MySQL server limitations.
                 //
                 $parent_enumeral_expression = 'parent_enumeral is null';
                 //
                 // RODBYNAM0
                 //
                 $enumeral = 'RODBYNAM0';
                 echo "   <tr>\n"
                    . "      <td><b>Simplified ROD sorted by Name &nbsp; &nbsp; [$enumeral]</b><br><i>(complex)</i></td>\n"
                    . "      <td align=right>\n"
                    . "         <form action=analyze.phtml method=post>\n"
                    . "            <input type=hidden name=bpn value=$bpn>\n"
                    . "            <input type=hidden name=algorithm value=$enumeral>\n"
                    . "            <input type=hidden name=parent_enumeral value=$enumeral>\n"
                    . "            <input type=submit value=\"Go!\">\n"
                    . "         </form>\n"
                    . "      </td>\n"
                    . "   </tr>\n"
                    . "   <tr>\n"
                    . "      <td colspan=2><blockquote><i>\n"
                    . "<p>This Go! button gives you access to a "
                    . "simplified version of the Resident/Occupant Database (ROD) <u>sorted by name</u>.</p>\n"
                    . "<p>Sample output:</p><blockquote><pre>"
                    . "   ID     <b>NAME              </b>ADDRESS            CITY            ST\n"
                    . "   -----  <b>----              </b>-------            ----            --\n"
                    . "    4582  <b>AAGLAN K          </b>1222 NORTHVALE DR  VIRGINIA BEACH  VA\n"
                    . "     254  <b>ABANATHY CARLOS   </b>1411 SADLEBRED CT  VIRGINIA BEACH  VA\n"
                    . "   22004  <b>ABARCA STEWART M  </b>524 AYELSBURY LN   VIRGINIA BEACH  VA\n"
                    . "</pre>\n"
                    . "      </blockquote></i></blockquote><hr></td>\n"
                    . "   </tr>\n";
                 //
                 // RODBYADDR0
                 //
                 $enumeral = 'RODBYADDR0';
                 echo "   <tr>\n"
                    . "      <td><b>Simplified ROD sorted by Address &nbsp; &nbsp; [$enumeral]</b><br><i>(complex)</i></td>\n"
                    . "      <td align=right>\n"
                    . "         <form action=analyze.phtml method=post>\n"
                    . "            <input type=hidden name=bpn value=$bpn>\n"
                    . "            <input type=hidden name=algorithm value=$enumeral>\n"
                    . "            <input type=hidden name=parent_enumeral value=$enumeral>\n"
                    . "            <input type=submit value=\"Go!\">\n"
                    . "         </form>\n"
                    . "      </td>\n"
                    . "   </tr>\n"
                    . "   <tr>\n"
                    . "      <td colspan=2><blockquote><i>\n"
                    . "<p>This Go! button gives you a "
                    . "simplified version of the Resident/Occupant Database (ROD) <u>sorted by address</u>.</p>\n"
                    . "<p>This analysis performs extensive processing and "
                    . "<u>currently takes as long as 1-2 minutes</u>.&nbsp; Do "
                    . "<u>not</u> close or navigate away from this window once you press the Go! button.&nbsp; (You may, "
                    . "however, continue browsing in another window and you may run other programs.)</p>\n"
                    . "<p>Sample output:</p><blockquote><pre>"
                    . "   ID     NAME              <b>NUMB  STREET ADDR   CITY            ST</b>\n"
                    . "   -----  ----              <b>----  -----------   ----            --</b>\n"
                    . "   22004  RUMBAUGH STEWART  <b>1220  NORTHVALE DR  VIRGINIA BEACH  VA</b>\n"
                    . "    4582  HUMPHREY K        <b>1224  NORTHVALE DR  VIRGINIA BEACH  VA</b>\n"
                    . "   10254  LEDGARD CARLOS    <b>1228  NORTHVALE DR  VIRGINIA BEACH  VA</b>\n"
                    . "</pre>\n"
                    . "      </blockquote></i></blockquote><hr></td>\n"
                    . "   </tr>\n";
                 //
                 // POPNAMCNT
                 //
                 $enumeral = 'POPNAMCNT';
                 echo "   <tr>\n"
                    . "      <td><b>\"Popular\" names &nbsp; &nbsp; [$enumeral]</b><br><i>(complex)</i></td>\n"
                    . "      <td align=right>\n"
                    . "         <form action=analyze.phtml method=post>\n"
                    . "            <input type=hidden name=bpn value=$bpn>\n"
                    . "            <input type=hidden name=algorithm value=$enumeral>\n"
                    . "            <input type=hidden name=parent_enumeral value=$enumeral>\n"
                    . "            <input type=submit value=\"Go!\">\n"
                    . "         </form>\n"
                    . "      </td>\n"
                    . "   </tr>\n"
                    . "   <tr>\n"
                    . "      <td colspan=2><blockquote><i>\n"
                    . "<p>This Go! button gives you a list of the names in the ROD that are associated with more than "
                    . "one address.</p>\n"
                    . "<p>Sample output:</p><blockquote><pre>"
                    . "   NAME                          OCCURRENCES\n"
                    . "   ----                          -----------\n"
                    . "   SECRETARY OF VETERAN AFFAIRS  43\n"
                    . "   COMMUNITY ALTERNATIVES CORP   37\n"
                    . "   CITY REDEVELOPMENT AUTHORITY  28\n"
                    . "</pre>\n"
                    . "      </blockquote></i></blockquote><hr></td>\n"
                    . "   </tr>\n";
                 break;
                 }
              case is_integer(strpos($parent_enumeral_expression,'RODBYNAM0')):
                 {
                 $qry = "select ceiling(count(*)/$chunk_size) as num_parts from rod_by_name";
                 extract(mysqli_fetch_array($db_link->query($qry)));  // Sets $num_parts.
                 echo "   <tr>\n"
                    . "      <form action=analyze.phtml method=post>\n"
                    . "         <input type=hidden name=bpn value=$bpn>\n"
                    . "         <input type=hidden name=format value=html>\n"
                    . "         <input type=hidden name=algorithm value=RODBYNAMSV>\n"
                    . "         <input type=hidden name=parent_enumeral value=RODBYNAMSV>\n"
                    . "      <td><b>SCREEN VIEW of Simplified ROD sorted by Name [RODBYNAMSV]</b></td>\n"
                    . "      <td align=right>\n"
                    . "         <input type=submit value=\"Go!\">\n"
                    . "      </td>\n"
                    . "   </tr>\n"
                    . "   <tr>\n"
                    . "      <td colspan=2><blockquote><i>\n"
                    . "         <p>Because of server limitations, KEYclick can only present about 1000 rows of data at a "
                    . "            time.&nbsp;  Specify below which part of the table you'd like to see.&nbsp; Allow up "
                    . "            a minute for the server to display the data.</p>\n"
                    . "         <blockquote>\n"
                    . "            <b>"
                    . "               View part "
                    . "                  <select name=part_num>";
                 for ($i = 1; $i <= $num_parts; $i++)
                    {
                    $top_offset = ($i - 1)*$chunk_size;
                    $qry = "select left(name,7) as top_name from rod_by_name limit $top_offset,1";
                    extract(mysqli_fetch_array($db_link->query($qry)));  // Sets $top_name.
                    if ($i < $num_parts)
                       {
                       $bottom_offset = ($i*$chunk_size - 1);
                       $qry = "select left(name,7) as bottom_name from rod_by_name limit $bottom_offset,1";
                       extract(mysqli_fetch_array($db_link->query($qry)));  // Sets $bottom_name.
                       }
                    else
                       {
                       $bottom_name = "[end]";
                       }
                    echo "<option value=$i>$i ($top_name - $bottom_name)</option>\n";
                    }
                 echo "                  </select>"
                    . "               of $num_parts."
                    . "            </b>\n"
                    . "         </blockquote>\n"
                    . "         <p>To get the data in much larger chunks, see the ZIP FILE options below.</p>\n"
                    . "         <hr>\n"
                    . "      </td>\n"
                    . "      </form>\n"
                    . "   </tr>\n";
                 break;
                 }
              case is_integer(strpos($parent_enumeral_expression,'RODBYADDR0')):
                 {
                 $qry = "select ceiling(count(*)/$chunk_size) as num_parts from rod_by_addr";
                 extract(mysqli_fetch_array($db_link->query($qry)));  // Sets $num_parts.
                 echo "   <tr>\n"
                    . "      <form action=analyze.phtml method=post>\n"
                    . "         <input type=hidden name=bpn value=$bpn>\n"
                    . "         <input type=hidden name=format value=html>\n"
                    . "         <input type=hidden name=algorithm value=RODBYADDRSV>\n"
                    . "         <input type=hidden name=parent_enumeral value=RODBYADDRSV>\n"
                    . "      <td><b>SCREEN VIEW of Simplified ROD sorted by Address [RODBYADDRSV]</b></td>\n"
                    . "      <td align=right>\n"
                    . "         <input type=submit value=\"Go!\">\n"
                    . "      </td>\n"
                    . "   </tr>\n"
                    . "   <tr>\n"
                    . "      <td colspan=2><blockquote><i>\n"
                    . "         <p>Because of server limitations, KEYclick can only present about 1000 rows of data at a "
                    . "            time.&nbsp;  Specify below which part of the table you'd like to see.&nbsp; Allow up "
                    . "            a minute for the server to display the data.</p>\n"
                    . "         <blockquote>\n"
                    . "            <b>"
                    . "               View part "
                    . "                  <select name=part_num>";
                 for ($i = 1; $i <= $num_parts; $i++)
                    {
                    $top_offset = ($i - 1)*$chunk_size;
                    $qry = "select left(state,2) as top_state "
                       . "   , left(city,4) as top_city "
                       . "   , left(street,4) as top_street "
                       . "   , left(numb,4) as top_numb "
                       . "from rod_by_addr limit $top_offset,1";
                    extract(mysqli_fetch_array($db_link->query($qry)));  // Sets $top_* vars.
                    $top_combo = "$top_numb-$top_street-$top_city-$top_state";
                    if ($i < $num_parts)
                       {
                       $bottom_offset = ($i*$chunk_size - 1);
                       $qry = "select left(state,2) as bottom_state "
                          . "   , left(city,4) as bottom_city "
                          . "   , left(street,4) as bottom_street "
                          . "   , left(numb,4) as bottom_numb "
                          . "from rod_by_addr limit $bottom_offset,1";
                       extract(mysqli_fetch_array($db_link->query($qry)));  // Sets $bottom_* vars.
                       $bottom_combo = "$bottom_numb-$bottom_street-$bottom_city-$bottom_state";
                       }
                    else
                       {
                       $bottom_combo = "[end]";
                       }
                    echo "<option value=$i>$i ($top_combo -- $bottom_combo)</option>\n";
                    }
                 echo "                  </select>"
                    . "               of $num_parts."
                    . "            </b>\n"
                    . "         </blockquote>\n"
                    . "         <p>To get the data in much larger chunks, see the ZIP FILE options below.</p>\n"
                    . "         <hr>\n"
                    . "      </td>\n"
                    . "      </form>\n"
                    . "   </tr>\n";
                 break;
                 }
              }
              //
              $sql = "select short_description"
              . " , enumeral"
              . " , long_description"
              . " , `sql`"
              . " , be_avail_as_html"
              . " , be_avail_as_zip"
              . " from analysis"
              . " where agency='$agency'"
              .   " and " . preg_replace('/=(.+)/',"='$1'",$parent_enumeral_expression) // It was not safe to pass string delimiters to this routine in a GET or POST parameter, but we know anything to the right of the equals sign needs them.
              . " order by position";
              $result = $db_link->query($sql)
                 or die("Retrieval of analyses failed with error: " . mysqli_error($db_link));
              //
              if (!mysqli_num_rows($result))
                 {
                 echo "<tr><td><p>None</p></td></tr>";
                 }
              else
                 {
                 while ($row = mysqli_fetch_array($result))
                    {
                    $short_description = $long_description = $sql = $be_avail_as_html = $be_avail_as_zip = "";
                    extract($row);
                    echo "   <tr>\n"
                       . "      <td><b>$short_description &nbsp; &nbsp; [$enumeral]</b></td>\n"
                       . "      <td align=right>\n"
                       . "         <form action=analyze.phtml method=post>\n"
                       . "            <input type=hidden name=bpn value=$bpn>\n"
                       . "            <input type=hidden name=parent_enumeral value=$enumeral>\n"
                       . "            <input type=hidden name=sql_query value=\"" . kix\k::ShieldedValueOfString($sql) . "\">\n";
                    if (($be_avail_as_html == 'TRUE') && ($be_avail_as_zip == 'TRUE'))
                       {
                       echo "            <input type=radio name=format value=html checked>View on screen\n"
                          . "               &nbsp;&nbsp;&nbsp;\n"
                          . "            <input type=radio name=format value=zip>Download as ZIP file\n"
                          . "               &nbsp;&nbsp;&nbsp;\n";
                       }
                    else if ($be_avail_as_html == 'TRUE')
                       {
                       echo "            <input type=hidden name=format value=html>(Screen view only)\n"
                          . "               &nbsp;&nbsp;&nbsp;\n";
                       }
                    else if ($be_avail_as_zip == 'TRUE')
                       {
                       echo "            <input type=hidden name=format value=zip>(Zip file only)\n"
                          . "               &nbsp;&nbsp;&nbsp;\n";
                       }
                    echo "            <input type=hidden name=be_drill_down_available value=" . ($enumeral == "OUTOFAREA" || $enumeral == "POPNAMCNTSV" ? "FALSE" : "TRUE") . ">\n";
                    echo "            <input type=submit value=\"Go!\">\n"
                       . "         </form>\n"
                       . "      </td>\n"
                       . "   </tr>\n"
                       . "   <tr>\n"
                       . "      <td colspan=2><blockquote><i>$long_description</i></blockquote><hr></td>\n"
                       . "   </tr>\n";
                    }
                 }
              echo "</table>\n";
              }
        ?>
        <br>
        <p><small><small><em><pre>$Id: form-analyze.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $</pre></em></small></small>
      </td>
    </tr>
  </table>
</body>

</html>
