<?
//
// $Id: form-export-full.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head><title>KEYclick - Export Full ROD</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table>
           <tr>
              <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
              <td>
                 <h6 align="center"><a href="javascript:close();">KEYCLICK SYSTEM</a></h6>
                 <h1 align="center">Export Full ROD</h1>
              </td>
              <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
              <td>
                <?
                PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"eye-candy",1);
                ?>
              </td>
           </tr>
        </table>
        <hr>
        <br>
        <?
           $agency = BeValidBoardingPass($db_link,$bpn);
           if ($agency == "")
              {
              KickOff();
              }
           else
              {
              //
              extract(  //Sets $num_rows
                 mysqli_fetch_array(
                    $db_link->query("select count(*) as num_rows from resident_base where agency='$agency'")));
              //
              extract(  //Sets $chunk_size
                 mysqli_fetch_array(
                    $db_link->query("select value as chunk_size from tuning_parm where name='export-chunk-size'")));
              //
              $num_chunks = ceil($num_rows/$chunk_size);
              ?>
              <p>Because of its size, the Full ROD must be downloaded as multiple ZIP files.&nbsp; KEYclick
                 recommends that you deliver the ZIP files, unaltered, to the vendor via email or floppy
                 disk.</p>
              <p><b>Please <u>WAIT PATIENTLY</u> after clicking a button.&nbsp; In each case, it will take a while for the
                 server to crunch the data before starting the download.</b></p>
              <blockquote>
                 <?
                 for ($i = 1; $i <= $num_chunks; $i++)
                    {
                    $sql = "select resident_base.id "
                       . "   ,resident_base.name "
                       . "   ,concat (house_num,' ',street.name) as address1 "
                       . "   ,city.name as city "
                       . "   ,state.abbreviation as state "
                       . "   ,null as zip "
                       . "from resident_base "
                         . " join street on (street.id=resident_base.street_id)"
                         . " join city on (city.id=street.city_id)"
                         . " join state on (state.id=city.state_id)"
                       . "where agency = '$agency' "
                       . "limit " . ($i - 1)*$chunk_size . "," . $chunk_size;
                    echo "<form action=export.phtml method=post>\n"
                       . "   <input type=hidden name=bpn value=" . $bpn . ">\n"
                       . "   <input type=hidden name=filename value=resident-part-" . $i . "-of-" . $num_chunks . ">\n"
                       . "   <input type=hidden name=whole_query value=\"$sql\">\n"
                       . "   <input type=submit value=\"Download Full ROD Part " . $i . "\">\n"
                       . "</form>\n";
                    }
                 ?>
              </blockquote>
              <?
              }
        ?>
        <br>
        <p><small><small><em><pre>$Id: form-export-full.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $</pre></em></small></small>
      </td>
    </tr>
  </table>
</body>

</html>
