<?
//
// $Id$
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
require_once("f_runmode.phtml");
$mode = "";
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
//
if (RunMode($PHP_SELF)) error_reporting(E_ALL);
//
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
//
$connected = (ConnectSelectDbInstanceUNPUBLISHED($db_link) == "TRUE");
?>
<html>

<head><title>KEYclick - Export ROD</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <?
           PutLibPhotoRandomPlaced("eye-candy",1);
           $connected = (ConnectSelectDbInstanceUNPUBLISHED($db_link) == "TRUE");
           ?>
        </td><td>
           <h6 align="center">
              <a href="<? echo HomePageUrl(); ?>">KEYCLICK SYSTEM</a></h6>
           <h1 align="center">Export ROD</h1>
        </td></tr></table>
        <hr>
        <br>
        <?
        if ($connected != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>KEYclick's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
           </blockquote>            
           </b>
           <?
           }
        else
           {
           //
           $agency = BeValidBoardingPass($db_link,$bpn,$mode);
           if ($agency == "")
              {
              KickOff($mode);
              }
           else
              {
              ?>
              <p>Specify which kind of ROD you want to export:</p>
              <table cellspacing=10>
                 <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top><b><a href=<? echo $mode; ?>form-export-full.phtml?bpn=<? echo $bpn; ?>>Full</b></a></td><td valign=top>Export the entire ROD, suitable for a <i>total saturation mailout</i>.</td>
                 <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top nowrap><b><a href=<? echo $mode; ?>form-export-follow-up.phtml?bpn=<? echo $bpn; ?>>Follow-up</b></a></td><td valign=top>This is the full ROD <i>minus</i> records associated with recent donations.&nbsp; This option gives you the chance to define what "recent" means.</td>
              </table>
              <br>
              <hr>
              <?
              }
           }
        ?>
        <br>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
      </td>
    </tr>
  </table>
</body>

</html>
