<?
//
// $Id: form-add-donation-ooa.phtml 7279 2020-07-04 00:50:55Z kevinanlipscomb $
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$bpn = $bpn;
$add_and_cancel = $add_and_cancel;
$add_and_repeat = $add_and_repeat;
$cancel = $cancel;
$undo = $undo;
$cross_id = $cross_id;
//
error_reporting(E_ALL);
//
if (isset($address1)) $address1 = kix\k::Safe($address1,kix\k::PhpValueOf_safe_hint_type("POSTAL_STREET_ADDRESS"));
if (isset($amount)) $amount = kix\k::Safe($amount,kix\k::PhpValueOf_safe_hint_type("REAL_NUM"));
if (isset($city)) $city = kix\k::Safe($city,kix\k::PhpValueOf_safe_hint_type("POSTAL_STREET_ADDRESS"));
if (isset($in_mem_of)) $in_mem_of = kix\k::Safe($in_mem_of,kix\k::PhpValueOf_safe_hint_type("PUNCTUATED"));
if (isset($method)) $method = kix\k::Safe($method,kix\k::PhpValueOf_safe_hint_type("ALPHA"));
if (isset($name)) $name = kix\k::Safe($name,kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME"));
if (isset($note)) $note = kix\k::Safe($note,kix\k::PhpValueOf_safe_hint_type("PUNCTUATED"));
if (isset($per_clerk_seq_num)) $per_clerk_seq_num = kix\k::Safe($per_clerk_seq_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($state)) $state = kix\k::Safe($state,kix\k::PhpValueOf_safe_hint_type("ALPHA"));
if (isset($zip)) $zip = kix\k::Safe($zip,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_NUM"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_formattednoteappendage.phtml");
require_once("f_emailaddrofbpn.phtml");
require_once("f_methodselectionlist.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
?>
<html>

<head>
<title>KEYclick - Log new out-of-area donation</title>
</head>

<? BodyOpen("CurrentOperation.last_name"); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <h6 align="center"><a href="javascript:close();">KEYCLICK SYSTEM</a></h6>
        <h1 align="center">Log new out-of-area donation</h1>
        <hr>
        <br>
        <?
           $agency = BeValidBoardingPass($db_link,$bpn);
           if ($agency == "")
              {
              KickOff();
              }
           else
           {
           $feedback_column_width_percentage = 25;
           echo "<table width=100%><tr>"
              . "<td width=$feedback_column_width_percentage% valign=top bgcolor=#F7F7F7 cellspacing=10>"
              . "<p><b><u>Previous operation</u></b></p>\n";
           if (($add_and_repeat) || ($add_and_cancel))
              {
              //
              // User indicated that data should be saved.  Validate parameters.
              //
              echo "<small>\n";
              //
              if (
                    ($last_name != "")
                 and
                    ($address1 != "")
                 and
                    ($city != "")
                 and
                    ($state != "")
                 and
                    ($zip != "")
                 and
                    (($amount != "") && is_numeric($amount))
                 )
              // then
                 {
                 if ($apt_num) $street_num = trim($street_num) . "-" . trim($apt_num);
                 //
                 $name = strtoupper(trim($last_name) . " " . trim($name_detail));
                 $address1 = strtoupper(trim($street_num) . " " . trim($address1));
                 $city = strtoupper(trim($city));
                 $state = strtoupper(trim($state));
                 $zip = strtoupper(trim($zip));
                 //
                 extract(mysqli_fetch_array($db_link->query("select max(id)+1 as new_id from resident_base")));
                 //
                 $result = $db_link->query
                    (
                    "insert into resident_journal "
                    .  "set name='" . addslashes($name) . "' "
                    .  "   , address1='" . addslashes($address1) . "' "
                    .  "   , city='" . addslashes($city) . "' "
                    .  "   , state='" . addslashes($state) . "' "
                    .  "   , zip='" . addslashes($zip) . "' "
                    .  "   , id=0 "
                    .  "   , op='UPDATE' "
                    .  "   , user_email_addr='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                    .  "   , amount='" . $amount . "' "
                    )
                    or die("Journal entry failed with error: " . mysqli_error($db_link));
                 //
                 // Determine next value for per_clerk_seq_num.
                 //
                 $per_clerk_seq_num = 1;
                 extract
                    (
                    mysqli_fetch_array
                       (
                       $db_link->query
                          (
                          "select ifnull(max(per_clerk_seq_num)+1,1) as per_clerk_seq_num from donation "
                          . " where entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                          )
                       )
                    );
                 //
                 // Suspend check for prior donations -- such a check is not appropriate in this case.
                 //
                 $db_link->query
                    ($qry =
                    "insert into donation "
                    .  "set id=0 "
                    .  "   , amount=$amount "
                    .  "   , date=CURRENT_DATE "
                    .  "   , method='$method' "
                    .  "   , in_mem_of='" . addslashes(trim($in_mem_of)) . "' "
                    .  "   , note='" . addslashes(trim($note)) . "' "
                    .  "   , entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                    .  "   , per_clerk_seq_num=$per_clerk_seq_num "
                    )
                    or die("Insert failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                 $db_link->query($qry = "update resident_base set year_of_last_appeal_to_become_a_donor = null where id = 0")
                    or die("Update failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                 //
                 echo "<table width=100%><tr><td><b>SUCCEEDED</b></td>\n"
                    . "<td align=right><form action=form-add-donation-ooa.phtml>\n"
                    . "   <input type=hidden name=bpn value=$bpn>\n"
                    . "   <input type=hidden name=per_clerk_seq_num value=$per_clerk_seq_num>\n"
                    . "   <input type=submit name=undo value=Undo></form></td></tr></table>\n"
                    . "<small><dl>\n"
                    . "<dt>Journaled data:</dt><dd>$name<br>$address1<br>$city $state $zip</dd>\n"
                    . "<dt>Amount:</dt><dd>\$$amount</dd>\n"
                    . "<dt>Method:</dt><dd>$method</dd>\n"
                    . "<dt>In memory of:</dt><dd>$in_mem_of&nbsp;</dd>\n"
                    . "<dt>Note:</dt><dd>$note&nbsp;</dd>\n"
                    . "</dl>\n"
                    . "<br/>\n"
                    . "<form action='https://frompaper2web.com/OscarTRACK/protected/donation_ack_letter.aspx' method=post>\n"
                    .   "<input type=hidden name=agency value='$agency'>\n"
                    .   "<input type=hidden name=donor_name value='$name'>\n"
                    .   "<input type=hidden name=address value='$address1'>\n"
                    .   "<input type=hidden name=city value='$city'>\n"
                    .   "<input type=hidden name=state value='$state'>\n"
                    .   "<input type=hidden name=amount value='$amount'>\n"
                    .   "<input type=hidden name=date value=''>\n"
                    .   "<input type=submit name=donation_ack_letter value='Gen ack letter'>\n"
                    . "</form>\n"
                    . "</small>\n";
                 }
              else
                 {
                 echo "<p><b>FAILED</b></p>\n"
                    . "<p><b>One or more fields were missing or invalid.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the "
                    . "problem.</b></p>\n";
                 }
              //
              echo "</small>\n";
              //
              $name = $address1 = $city = $state = $zip = $amount = $method = $in_mem_of = $note = "";
              //
              }
           elseif ($undo)
              {
              $db_link->query
                 (
                 "delete from donation "
                 . "where entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                 . "   and per_clerk_seq_num=$per_clerk_seq_num "
                 )
                 or die("Undo failed with error: " . mysqli_error($db_link));
              //
              echo "<p><b>UNDONE</b></p>\n";
              }
           else
              {
              echo "<p>None</p>\n";
              }
           //
           echo "</td><td width=5%>&nbsp;</td><td valign=top>\n";
           //
           if ((!$add_and_cancel) && (!$cancel))
              {
              echo "<p><b><u>Current operation:</u></b></p>\n"
                 . "<form name=CurrentOperation action=form-add-donation-ooa.phtml method=post>\n"
                 . "   <input type=hidden name=bpn value=$bpn>\n"
                 . "   <table>\n"
                 . "      <tr><td align=right>Last name:</td><td colspan=2><input type=text name=last_name size=20 maxlength=20></td></tr>\n"
                 . "      <tr><td align=right>First/other name(s):</td><td colspan=2><input type=text name=name_detail size=30 maxlength=30></td></tr>\n"
                 . "      <tr><td align=right>House/building #:</td><td colspan=2><input type=text name=street_num size=6 maxlength=10></td></tr>\n"
                 . "      <tr><td align=right>Street name:</td><td colspan=2><input type=text name=address1 size=50 maxlength=50></td></tr>\n"
                 . "      <tr><td align=right>Apt #:</td><td colspan=2><input type=text name=apt_num size=4 maxlength=6></td></tr>\n"
                 . "      <tr><td align=right>City:</td><td colspan=2><input type=text name=city size=35 maxlength=35></td></tr>\n"
                 . "      <tr><td align=right>State:</td><td colspan=2><input type=text name=state size=2 maxlength=2></td></tr>\n"
                 . "      <tr><td align=right>Zip code:</td><td colspan=2><input type=text name=zip size=10 maxlength=10></td></tr>\n"
                 . "      <tr><td align=right>Amount: $</td><td colspan=2><input type=text name=amount size=6 maxlength=10></td></tr>\n"
                 . "      <tr><td align=right>Received via:</td><td colspan=2>\n";
              echo MethodSelectionList($db_link,$agency,"LOVELETTER");
              echo "      </td></tr>\n"
                 . "      <tr><td align=right>In memory of:</td><td colspan=2><input type=text name=in_mem_of size=60 maxlength=60></td></tr>\n"
                 . "      <tr><td align=right>Note:</td><td colspan=2><textarea name=note cols=40 rows=4 wrap></textarea></td></tr>\n"
                 . "      <tr>\n"
                 . "         <td colspan=2>\n"
                 . "            <table width=100%>\n"
                 . "               <tr>\n"
                 . "                  <td align=center><input type=submit name=add_and_repeat value=\"Add and Repeat\"></td>\n"
                 . "                  <td align=center><input type=submit name=add_and_cancel value=\"Add and Stop\"></td>\n"
                 . "                  <td align=center><input type=submit name=cancel value=Cancel></td>\n"
                 . "               </tr>\n"
                 . "            </table>\n"
                 . "         </td>\n"
                 . "      </tr>\n"
                 . "   </table>\n"
                 . "</form>\n";
              $cross_id = "";
              }
           else
              {
              echo "<p><b><a href=\"javascript:close();\">Go to <b>Main KEYclick</b> page.</a></b></p>\n";
              }
           echo "</td></tr></table>\n";
           //
           } // BeValidBoardingPass
        ?>
        <br>
        <p><small><small><em><pre>$Id: form-add-donation-ooa.phtml 7279 2020-07-04 00:50:55Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>
