<?
//
// $Id: form-edit-donation.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$bpn = $bpn;
$be_interested_in_patient_care = $be_interested_in_patient_care;
$be_interested_in_support = $be_interested_in_support;
$be_interested_in_volunteering = $be_interested_in_volunteering;
$be_interested_in_bequesting = $be_interested_in_bequesting;
$add_and_cancel = $add_and_cancel;
$add_and_repeat = $add_and_repeat;
$cancel = $cancel;
$undo = $undo;
$cross_id = $cross_id;
//
error_reporting(E_ALL);
//
if (isset($amount)) $amount = kix\k::Safe($amount,kix\k::PhpValueOf_safe_hint_type("REAL_NUM"));
if (isset($id)) $id = kix\k::Safe($id,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($in_mem_of)) $in_mem_of = kix\k::Safe($in_mem_of,kix\k::PhpValueOf_safe_hint_type("PUNCTUATED"));
if (isset($method)) $method = kix\k::Safe($method,kix\k::PhpValueOf_safe_hint_type("ALPHA"));
if (isset($note)) $note = kix\k::Safe($note,kix\k::PhpValueOf_safe_hint_type("PUNCTUATED"));
if (isset($per_clerk_seq_num)) $per_clerk_seq_num = kix\k::Safe($per_clerk_seq_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_formattednoteappendage.phtml");
require_once("f_emailaddrofbpn.phtml");
require_once("f_methodselectionlist.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
?>
<html>

<head>
<title>KEYclick - Edit donation record</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <h6 align="center"><a href="javascript:close();">KEYCLICK SYSTEM</a></h6>
        <h1 align="center">Edit donation record</h1>
        <hr>
        <br>
        <?
           $agency = BeValidBoardingPass($db_link,$bpn);
           if ($agency == "")
              {
              KickOff();
              }
           else
           {
           $feedback_column_width_percentage = 25;
           echo "<table width=100%><tr>"
              . "<td width=$feedback_column_width_percentage% valign=top bgcolor=#F7F7F7 cellspacing=10>"
              . "<p><b><u>Previous operation</u></b></p>\n";
           if (($add_and_repeat) || ($add_and_cancel))
              {
              //
              // User indicated that data should be saved.  Validate parameters.
              //
              echo "<small>\n";
              //
              if (
                    (($id != "") && is_numeric($id))
                 and
                    (($amount != "") && is_numeric($amount))
                 )
              // then
                 {
                 //
                 // Determine next value for per_clerk_seq_num.
                 //
                 $per_clerk_seq_num = 1;
                 extract
                    (
                    mysqli_fetch_array
                       (
                       $db_link->query
                          (
                          "select ifnull(max(per_clerk_seq_num)+1,1) as per_clerk_seq_num from donation "
                          . " where entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                          )
                       )
                    );
                 //
                 // Check for prior donations.
                 //
                 $num_priors = "";
                 $result = $db_link->query("select count(*) as num_priors from donation where id=$id")
                    or die("Check for priors failed with error: " . mysqli_error($db_link));
                 extract(mysqli_fetch_array($result));
                 //
                 $db_link->query
                    ($qry =
                    "insert into donation "
                    .  "set id=$id "
                    .  "   , amount=$amount "
                    .  "   , date=CURRENT_DATE "
                    .  "   , be_interested_in_patient_care=" . ($be_interested_in_patient_care ? "TRUE" : "FALSE")
                    .  "   , be_interested_in_support=" . ($be_interested_in_support ? "TRUE" : "FALSE")
                    .  "   , be_interested_in_volunteering=" . ($be_interested_in_volunteering ? "TRUE" : "FALSE")
                    .  "   , be_interested_in_bequesting=" . ($be_interested_in_bequesting ? "TRUE" : "FALSE")
                    .  "   , method='$method' "
                    .  "   , in_mem_of='" . addslashes(trim($in_mem_of)) . "' "
                    .  "   , note='" . addslashes(trim($note)) . "' "
                    .  "   , entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                    .  "   , per_clerk_seq_num=$per_clerk_seq_num "
                    )
                    or die("Insert failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                 //
                 $result = $db_link->query
                    (
                    "select resident_base.name"
                    . " , concat(house_num,' ',street.name) as address1"
                    . " , city.name as city"
                    . " , state.abbreviation as state"
                    . " , null as zip"
                    . " from resident_base"
                      . " join street on (street.id=resident_base.street_id)"
                      . " join city on (city.id=street.city_id)"
                      . " join state on (state.id=city.state_id)"
                    . " where resident_base.id='$id'"
                    )
                    or die("Master record lookup failed with error: " . mysqli_error($db_link));
                 extract(mysqli_fetch_array($result));
                 //
                 echo "<table width=100%><tr><td><b>SUCCEEDED</b></td>\n"
                    . "<td align=right><form action=form-add-donation.phtml>\n"
                    . "   <input type=hidden name=bpn value=$bpn>\n"
                    . "   <input type=hidden name=per_clerk_seq_num value=$per_clerk_seq_num>\n"
                    . "   <input type=submit name=undo value=Undo></form></td></tr></table>\n"
                    . "<small><dl>\n"
                    . "<dt>ROD#:</dt><dd>$id</dd>\n"
                    . "<dt>Lookup data:</dt>\n"
                    . "   <dd>\n"
                    . "      <a href=form-act-singly.phtml?bpn=$bpn&id=$id>"
                    . "         $name<br>$address1<br>$city $state $zip\n"
                    . "      </a>\n"
                    . "   </dd>\n";
                 if ($num_priors)
                    {
                    echo "<hr><a href=form-act-singly.phtml?bpn=$bpn&id=$id>$num_priors prior donation(s)</a> "
                       . "on record\n";
                    }
                 echo "<dt>Amount:</dt><dd>\$$amount</dd>\n"
                    . "<dt>Interested in patient care:</dt><dd>" . ($be_interested_in_patient_care ? "YES" : "no") . "&nbsp;</dd>\n"
                    . "<dt>Interested in support:</dt><dd>" . ($be_interested_in_support ? "YES" : "no") . "&nbsp;</dd>\n"
                    . "<dt>Interested in volunteering:</dt><dd>" . ($be_interested_in_volunteering ? "YES" : "no") . "&nbsp;</dd>\n"
                    . "<dt>Interested in bequesting:</dt><dd>" . ($be_interested_in_bequesting ? "YES" : "no") . "&nbsp;</dd>\n"
                    . "<dt>Method:</dt><dd>$method</dd>\n"
                    . "<dt>In memory of:</dt><dd>$in_mem_of&nbsp;</dd>\n"
                    . "<dt>Note:</dt><dd>$note&nbsp;</dd>\n"
                    . "</dl>\n\n"
                    . "</small>\n";
                 }
              else
                 {
                 echo "<p><b>FAILED</b></p>\n"
                    . "<p><b>One or more fields were missing or invalid.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the "
                    . "problem.</b></p>\n";
                 }
              //
              echo "</small>\n";
              //
              $id = $name = $address1 = $city = $state = $zip = $amount = $be_interested_in_patient_care = $be_interested_in_support = $be_interested_in_volunteering =
                 $be_interested_in_bequesting = $method = $in_mem_of = $note = "";
              //
              }
           elseif ($undo)
              {
              $db_link->query
                 (
                 "delete from donation "
                 . "where entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                 . "   and per_clerk_seq_num=$per_clerk_seq_num "
                 )
                 or die("Undo failed with error: " . mysqli_error($db_link));
              //
              echo "<p><b>UNDONE</b></p>\n";
              }
           else
              {
              echo "<p>None</p>\n";
              }
           //
           echo "</td><td width=5%>&nbsp;</td><td valign=top>\n";
           //
           if ((!$add_and_cancel) && (!$cancel))
              {
              //
              // Break the given ISO date string into its constituent parts.
              //
              list($year_num,$month_num,$day_num) = sscanf($cross_date,"%4u-%2u-%2u"); // sscanf($cross_date,"%4u-%2u-%2u",$year_num,$month_num,$day_num); //would not work under PeachPie 0.9.961.
              //
              echo "<p><b><u>Current operation:</u></b></p>\n"
                 . "<form name=CurrentOperation action=perform-update-donation.phtml method=post>\n"
                 . "   <input type=hidden name=bpn value=$bpn>\n"
                 . "   <input type=hidden name=cross_id value=$cross_id>\n"
                 . "   <input type=hidden name=cross_entered_by value=$cross_entered_by>\n"
                 . "   <input type=hidden name=cross_per_clerk_seq_num value=$cross_per_clerk_seq_num>\n"
                 . "   <table>\n"
                 . "      <tr><td align=right>ROD #:</td><td colspan=2><b>$cross_id</b></td></tr>\n"
                 . "      <tr><td align=right valign=top>Name:<br>Address:</td><td colspan=2><b>$cross_name<br>$cross_address<br>$cross_city $cross_state $cross_zip</b></td></tr>\n"
                 . "      <tr><td align=right>Entry sub ID:</td><td colspan=2><b>$cross_entered_by-$cross_per_clerk_seq_num</b></td></tr>\n"
                 . "      <tr>\n"
                 . "         <td align=right>Approximate date:</td>\n"
                 . "         <td colspan=2>\n"
                 . "            <table>\n"
                 . "               <tr><td colspan=3><hr></td></tr>\n"
                 . "               <tr>\n"
                 . "                  <td align=center>Year</td><td align=center>Month</td><td align=center>Day</td>\n"
                 . "               </tr>\n"
                 . "               <tr>\n"
                 . "                  <td align=center>\n"
                 . "                     <select name=year_num>\n"
                 . "               <option selected>$year_num</option>\n";
              for ($year_num_index = date('Y'); $year_num_index >= 1951; $year_num_index--)
                 {
                 echo "<option>$year_num_index</option>\n";
                 }
              echo "                     </select>\n"
                 . "                  </td>\n"
                 . "                  <td align=center>\n"
                 . "                     <select name=month_num>\n"
                 . "               <option selected>$month_num</option>\n"
                 . "               <option></option>";
              for ($month_num_index = 1; $month_num_index <= 12; $month_num_index++)
                 {
                 echo "<option>$month_num_index</option>\n";
                 }
              echo "                     </select>\n"
                 . "                  </td>\n"
                 . "                  <td align=center>\n"
                 . "                     <select name=day_num>\n"
                 . "               <option selected>$day_num</option>\n"
                 . "               <option></option>";
              for ($day_num_index = 1; $day_num_index <= 31; $day_num_index++)
                 {
                 echo "<option>$day_num_index</option>\n";
                 }
              echo "                     </select>\n"
                 . "                  </td>\n"
                 . "               </tr>\n"
                 . "               <tr><td colspan=3><hr></td></tr>\n"
                 . "            </table>\n"
                 . "         </td>\n"
                 . "      </tr>\n"
                 . "      <tr><td align=right>Amount: $</td><td colspan=2><input type=text name=amount value=$cross_amount size=6 maxlength=10></td></tr>\n"
                  . "      <tr><td align=right>Interested in patient care:</td><td colspan=2><input type=checkbox name=be_interested_in_patient_care " . ($cross_be_interested_in_patient_care ? "checked" : "") . "></td></tr>\n"
                 . "      <tr><td align=right>Interested in support:</td><td colspan=2><input type=checkbox name=be_interested_in_support " . ($cross_be_interested_in_support ? "checked" : "") . "></td></tr>\n"
                 . "      <tr><td align=right>Interested in volunteering:</td><td colspan=2><input type=checkbox name=be_interested_in_volunteering " . ($cross_be_interested_in_volunteering ? "checked" : "") . "></td></tr>\n"
                 . "      <tr><td align=right>Interested in bequesting:</td><td colspan=2><input type=checkbox name=be_interested_in_bequesting " . ($cross_be_interested_in_bequesting ? "checked" : "") . "></td></tr>\n"
                 . "      <tr><td align=right>Received via:</td><td colspan=2>\n";
              echo MethodSelectionList($db_link,$agency,$cross_method);
              echo "      </td></tr>\n"
                 . "      <tr><td align=right>In memory of:</td><td colspan=2><input type=text name=in_mem_of value=\"$cross_in_mem_of\" size=60 maxlength=60></td></tr>\n"
                 . "      <tr><td align=right>Note:</td><td colspan=2><textarea name=note cols=40 rows=4 wrap>$cross_note</textarea></td></tr>\n"
                 . "      <tr>\n"
                 . "         <td colspan=2>\n"
                 . "            <table width=100%>\n"
                 . "               <tr>\n"
                 . "                  <td align=center><input type=submit name=save value=Save></td>\n"
                 . "                  <td align=center><input type=submit name=cancel value=Cancel></td>\n"
                 . "               </tr>\n"
                 . "            </table>\n"
                 . "         </td>\n"
                 . "      </tr>\n"
                 . "   </table>\n"
                 . "</form>\n";
              $cross_id = "";
              }
           else
              {
              echo "<p><b><a href=\"javascript:close();\">Go to <b>Main KEYclick</b> page.</a></b></p>\n";
              }
           echo "</td></tr></table>\n";
           //
           } // BeValidBoardingPass
        ?>
        <br>
        <p><small><small><em><pre>$Id: form-edit-donation.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>
