<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$save = $save;
$id = $id;
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_homepageurl.phtml");
require_once("f_bodyopen.phtml");
require_once("f_connectselectdb.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_formattednoteappendage.phtml");
require_once("f_emailaddrofbpn.phtml");
require_once("f_streetselectionlist.phtml");
require_once("f_cityselectionlist.phtml");
require_once("f_stateselectionlist.phtml");
?>
<html>

<head>
<title>KEYclick - Modify or remove resident record</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <h6 align="center"><a href=<? echo HomePageUrl(); ?>>KEYCLICK SYSTEM</a></h6>
        <h1 align="center">Modify or remove resident record</h1>
        <hr>
        <br>
        <?
        if (ConnectSelectDb("localhost","kalipso",Password(),"keyclick") != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>KEYclick's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
           </blockquote>            
           </b>
           <?
           }
        else
           {
           if (($agency = BeValidBoardingPass($bpn,$mode)) == "")
              {
              KickOff($mode);
              }
           else
           {
           //
           // Database is up.
           //
           $feedback_column_width_percentage = 25;
           echo "<table width=100%><tr>"
              . "<td width=$feedback_column_width_percentage% valign=top bgcolor=#F7F7F7 cellspacing=10>"
              . "<p><b><u>Previous operation</u></b></p>\n";
           if ($save)
              {
              //
              // User indicated that data should be saved.  Validate parameters.
              //
              echo "<small>\n";
              //
              if (($action == "update") or ($action == "delete"))
                 {
                 $result = mysql_query
                    (
                    "select resident_base.name as old_name "
                    .  " , concat(house_num,' ',street.name) as old_address1 "
                    .  " , city.name as old_city "
                    .  " , state.abbreviation as old_state "
                    .  " , null as old_zip "
                    .  " from " . $mode . "resident_base "
                       . " join street on (street.id=resident_base.street_id) "
                       . " join city on (city.id=street.city_id) "
                       . " join state on (state.id=city.state_id) "
                    .  " where resident_base.id=$id_to_save "
                    )
                    or die("Select failed with error: " . mysql_error());
                 //
                 extract(mysql_fetch_array($result));
                 }
              if ($action == "update")
                 {
                 if (
                       (($name = trim($name)) != "")
                    and
                       (($street_id = trim($street_id)) != "")
                    )
                 // then
                    {
                    $result = mysql_query
                       (
                       "update " . $mode . "resident_base "
                       .  "set name='" . addslashes($name) . "' "
                       .  "   , house_num='" . addslashes($house_num) . "' "
                       .  "   , street_id='" . addslashes($street_id) . "' "
                       .  "where id=$id_to_save "
                       .  "limit 1 "
                       )
                       or die("Update failed with error: " . mysql_error());
                    //
                    $result = mysql_query
                       (
                       "insert into " . $mode . "resident_journal "
                       .  "set name='" . addslashes($old_name) . "' "
                       .  "   , address1='" . addslashes($old_address1) . "' "
                       .  "   , city='" . addslashes($old_city) . "' "
                       .  "   , state='" . addslashes($old_state) . "' "
                       .  "   , zip='" . addslashes($old_zip) . "' "
                       .  "   , id=$id_to_save "
                       .  "   , op='UPDATE' "
                       .  "   , user_email_addr='" . EmailAddrOfBpn($bpn,$mode) . "' "
                       )
                       or die("Journal entry failed with error: " . mysql_error());
                    //
                    $result = mysql_query
                       (
                       "select resident_base.name "
                       .  " , concat(house_num,' ',street.name) as address1 "
                       .  " , city.name as city "
                       .  " , state.abbreviation as state "
                       .  " from " . $mode . "resident_base "
                          . " join street on (street.id=resident_base.street_id) "
                          . " join city on (city.id=street.city_id) "
                          . " join state on (state.id=city.state_id) "
                       .  " where resident_base.id=$id_to_save "
                       )
                       or die("Select failed with error: " . mysql_error());
                    //
                    extract(mysql_fetch_array($result));
                    //
                    echo "<p><b>SUCCEEDED</b></p>\n"
                       . "<small><dl>\n"
                       . "<dt>Resident ID:</dt><dd>$id_to_save</dd>\n"
                       . "<dt>Name:</dt><dd>$name</dd>\n"
                       . "<dt>Address:</dt><dd>$address1</dd>\n"
                       . "<dt>City:</dt><dd>$city</dd>\n"
                       . "<dt>State:</dt><dd>$state</dd>\n"
                       . "</dl></small>\n";
                    }
                 else
                    {
                    echo "<p><b><u>FAILED</u></b></p>\n"
                       . "<p><b>One or more fields were missing.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the "
                       . "problem.</b></p>\n";
                    }
                 }
              elseif ($action == "delete")
                 {
                 $result = mysql_query
                    (
                    "delete from " . $mode . "resident_base "
                    .  "where id=$id_to_save "
                    .  "limit 1"
                    )
                    or die("Delete failed with error: " . mysql_error());
                 //
                 $result = mysql_query
                    (
                    "insert into " . $mode . "resident_journal "
                    .  "set name='" . addslashes($old_name) . "' "
                    .  "   , address1='" . addslashes($old_address1) . "' "
                    .  "   , city='" . addslashes($old_city) . "' "
                    .  "   , state='" . addslashes($old_state) . "' "
                    .  "   , zip='" . addslashes($old_zip) . "' "
                    .  "   , id=$id_to_save "
                    .  "   , op='DELETE' "
                    .  "   , user_email_addr='" . EmailAddrOfBpn($bpn,$mode) . "' "
                    )
                    or die("Journal entry failed with error: " . mysql_error());
                 //
                 echo "<p><b>SUCCEEDED</b></p>\n"
                    . "<small>Resident ID $id_to_save has been deleted.</small>\n";
                 }
              else
                 {
                 echo "<p><b>FAILED</b></p>\n"
                    . "<p><b>Missing or unknown <u>action</u>.</p>\n";
                 }
              //
              echo "</small>\n";
              //
              $name = $address1 = $city = $state = $zip = "";
              //
              }
           else
              {
              echo "<p>None</p>\n";
              }
           //
           echo "</td><td width=5%>&nbsp;</td><td valign=top>\n";
           //
           if ($id != "")
              {
              //
              // Lookup record with specified ID.
              //
              $result = mysql_query
                 (
                 "select resident_base.name "
                 .  ", house_num"
                 .  ", street_id "
                 .  "from " . $mode . "resident_base "
                 .  "where resident_base.id='$id' "
                 )
                 or die("Query failed with error: " . mysql_error());
              $num_rows = mysql_num_rows($result);
              if ($num_rows)
                 {
                 extract(mysql_fetch_array($result));
                 //
                 // Retrieve any journal entries associated with this record.
                 //
                 $journal_query_result = mysql_query
                    (
                    "select *, date_format(timestamp,'%H:%i:%s on %e %b %Y') as timestamp_string "
                    .  "from " . $mode . "resident_journal "
                    .  "where id=$id order by timestamp desc"
                    )
                    or die("Journal query failed with error: " . mysql_error());
                 $num_journal_rows = mysql_num_rows($journal_query_result);
                 //
                 // Retrieve any donation entries associated with this record.
                 //
                 $donation_query_result = mysql_query
                    (
                    "select *, date_format(timestamp,'%H:%i:%s on %e %b %Y') as timestamp_string "
                    .  "from " . $mode . "donation "
                    .  "where id=$id order by date desc"
                    )
                    or die("Donation query failed with error: " . mysql_error());
                 $num_donations = mysql_num_rows($donation_query_result);
                 //
                 echo "<p><b><u>Current operation:</u></b></p>\n"
                    . "<blockquote>\n"
                    . "<form action=" . $mode . "form-act-singly.phtml method=post>\n"
                    . "   <input type=hidden name=bpn value=$bpn>\n"
                    . "   <input type=hidden name=id_to_save value=$id>\n";
                 if ($num_journal_rows or $num_donations)
                    {
                    echo "<ul>\n";
                    //
                    if ($num_donations)
                       {
                       extract
                          (
                          mysql_fetch_array
                             (
                             mysql_query("select sum(amount) as sum from " . $mode . "donation where id=$id group by id")
                             )
                          );
                       echo "<li><a href=#Donations>$num_donations donation"
                          . (($num_donations > 1) ? "s</a> totaling <b>\$$sum</b> are " : "</a> totaling <b>\$$sum</b> is ")
                          . "on file for this record.</li>\n";
                       }
                    //
                    if ($num_journal_rows)
                       {
                       echo "<li><a href=#History>$num_journal_rows journal "
                          . (($num_journal_rows == 1) ? 'entry</a> is ' : 'entries</a> are ' )
                          . "available for this record.</li>\n";
                       }
                    //
                    echo "</ul>\n";
                    }
                 echo "   <table>\n"
                    . "      <tr><td align=right><b>Resident ID:</b></td><td colspan=2><b>$id</b></td></tr>\n"
                    . "      <tr><td align=right>Name:</td><td colspan=2><input type=text name=name value=\"$name\" size=50 maxlength=50></td></tr>\n"
                    . "      <tr><td align=right>House #:</td><td colspan=2><input type=text name=house_num value=\"$house_num\" size=15 maxlength=15></td></tr>\n"
                    . "      <tr><td align=right>Street, City, State:</td><td colspan=2>";
                 StreetSelectionList($mode,$street_id);
                 echo "</td></tr>\n"
                    . "      <tr>\n"
                    . "         <td align=right valign=top>Action:</td>\n"
                    . "         <td colspan=2>\n"
                    . "            <input type=radio name=action value=update checked>Update<br>\n"
                    . "            <input type=radio name=action value=delete>Delete\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "      <tr><td colspan=3><hr></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td colspan=3 align=center>\n"
                    . "            Next Resident ID to modify/remove (optional):\n"
                    . "            <input type=text name=id value=\"\" maxlength=5 size=5>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "      <tr><td colspan=3><hr></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td colspan=3>\n"
                    . "            <table width=100%>\n"
                    . "               <tr>\n"
                    . "                  <td align=center><input type=submit name=save value=Save></td>\n"
                    . "                  <td align=center><input type=submit name=cancel value=Cancel></td>\n"
                    . "               </tr>\n"
                    . "            </table>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "   </table>\n"
                    . "</form>\n";
                 if ($num_donations)
                    {
                    echo "   <a name=Donations></a><p><br><b>Donations totaling \$$sum</b>, in reverse chronological order:</p>\n"
                       . "   <small><ol>\n";
                    for ($i = 1; $i <= $num_donations; $i++)
                       {
                       extract(mysql_fetch_array($donation_query_result));
                       echo "<li><b>\$$amount on year-month-day $date</b><br>\n"
                          . "<table><tr><td>&nbsp;&nbsp; </td><td>";
                       switch ($method)
                          {
                          case "BIZREPLY":
                             echo "In response to a fund drive appeal;<br>\n";
                             break;
                          case "INMEMOF":
                             echo "In memory of '$in_mem_of';<br>\n";
                             break;
                          case "UNSOLICITED":
                             echo "Unsolicited;<br>\n";
                             break;
                          case "WEB":
                             echo "Via the Internet;<br>\n";
                             break;
                          }
                       if (($method != "INMEMOF") and ($in_mem_of))
                          {
                          echo "Also in memory of '$in_mem_of';<br>\n";
                          }
                       switch ($prospectivity)
                          {
                          case "NONE":
                             break;
                          case "RESCUE":
                             echo "<b>Interested in volunteering for Patient Care</b>;<br>\n";
                             break;
                          case "SUPPORT":
                             echo "<b>Interested in volunteering for Non-Emergency Support</b>;<br>\n";
                             break;
                          }
                       if ($note)
                          {
                          echo "Note:&nbsp; <i>$note</i><br>\n";
                          }
                       echo "<small>(Entered by <a href=mailto:$entered_by><i>$entered_by</i></a> at $timestamp_string).</small><br>"
                          . "<table width=100%>\n"
                          . "   <tr>\n"
                          . "      <td>\n"
                          . "         <form action=" . $mode . "form-edit-donation.phtml method=post>\n"
                          . "            <input type=hidden name=bpn value=$bpn>\n"
                          . "            <input type=hidden name=cross_entered_by value=$entered_by>\n"
                          . "            <input type=hidden name=cross_per_clerk_seq_num value=$per_clerk_seq_num>\n"
                          . "            <input type=hidden name=cross_id value=$id>\n"
                          . "            <input type=hidden name=cross_name value=\"$name\">\n"
                          . "            <input type=hidden name=cross_address value=\"$address1\">\n"
                          . "            <input type=hidden name=cross_city value=\"$city\">\n"
                          . "            <input type=hidden name=cross_state value=\"$state\">\n"
                          . "            <input type=hidden name=cross_zip value=\"$zip\">\n"
                          . "            <input type=hidden name=cross_date value=$date>\n"
                          . "            <input type=hidden name=cross_amount value=$amount>\n"
                          . "            <input type=hidden name=cross_prospectivity value=$prospectivity>\n"
                          . "            <input type=hidden name=cross_in_mem_of value=\"$in_mem_of\">\n"
                          . "            <input type=hidden name=cross_method value=$method>\n"
                          . "            <input type=hidden name=cross_note value=\"$note\">\n"
                          . "            <input type=submit name=edit value=\"Edit above entry\">\n"
                          . "         </form>\n"
                          . "      </td>\n"
                          . "   </tr>\n"
                          . "</table>\n"
                          . "<hr></td></tr></table>\n";
                       }
                    echo "   </ol></small>\n";
                    }
                 if ($num_journal_rows)
                    {
                    echo "   <a name=History></a><p><br><b>Journal entries</b> in reverse chronological order:</p>\n"
                       . "   <small><ol>\n";
                    for ($i = 1; $i <= $num_journal_rows; $i++)
                       {
                       extract(mysql_fetch_array($journal_query_result));
                       echo "<li><p>\n";
                       switch ($op)
                          {
                          case "INSERT":
                             echo "Was added by <a href=mailto:$user_email_addr><i>$user_email_addr</i></a> ";
                             break;
                          case "UPDATE":
                             echo "Was:<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$name<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$address1<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$city $state $zip<br>\n";
                             echo "before <a href=mailto:$user_email_addr><i>$user_email_addr</i></a> updated it ";
                             break;
                          case "DELETE":
                             echo "Was:<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$name<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$address1<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$city $state $zip<br>\n";
                             echo "before <a href=mailto:$user_email_addr><i>$user_email_addr</i></a> deleted it ";
                             break;
                          }
                       echo "at $timestamp_string.</p></li>\n";
                       }
                    echo "   </ol></small>\n";
                    }
                 echo "</blockquote>\n";
                 }
              else
                 {
                 ?>
                 <p><b>No such Resident ID found.</b></p>
                 <blockquote>
                    <form action=<? echo $mode; ?>form-act-singly.phtml method=post>
                       Edit and retry:
                       <input type=hidden name=bpn value=<? echo $bpn; ?>>
                       <input type=text name=id maxlength=5 size=5 value=<? echo $id; ?>>
                       <input type=submit value="Go!">
                    </form>
                 </blockquote>
                 <?
                 }
              } // non-null $id
           else
              {
              //
              // No ID specified.
              //
              echo "<p><b>No Resident ID specified</b></p>\n"
                 . "<blockquote>\n"
                 . "   <form action=" . $mode . "form-act-singly.phtml method=post>\n"
                 . "      <input type=hidden name=bpn value=$bpn>\n"
                 . "      Specify a Resident ID:\n"
                 . "      <input type=text name=id maxlength=5 size=5 value=$id>\n"
                 . "      <input type=submit value=\"Go!\"><br>\n"
                 . "      <br>\n"
                 . "      -- or --<br>\n"
                 . "      <br>\n"
                 . "      <a href=" . $mode . "form-add-donation.phtml?bpn=$bpn>Go to <b>Log a NEW donation</b> page.</a><br>\n"
                 . "      <br>\n"
                 . "      -- or --<br>\n"
                 . "      <br>\n"
                 . "      <a href=" . $mode . "form-add-donation-old.phtml?bpn=$bpn>Go to <b>Log an OLD donation</b> page.</a><br>\n"
                 . "      <br>\n"
                 . "      -- or --<br>\n"
                 . "      <br>\n"
                 . "      <a href=" . $mode . "main.phtml?bpn=$bpn>Go to <b>Main KEYclick</b> page.</a>\n"
                 . "   </form>\n"
                 . "</blockquote>\n";
              }
           //
           echo "</td></tr></table>\n";
           //
           } // BeValidBoardingPass
           } // database up
        ?>
        <br>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>
