<?php
//
// $Id: form-add-donation-old.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$bpn = $bpn;
$be_interested_in_patient_care = $be_interested_in_patient_care;
$be_interested_in_support = $be_interested_in_support;
$be_interested_in_volunteering = $be_interested_in_volunteering;
$be_interested_in_bequesting = $be_interested_in_bequesting;
$method = $method;
$in_mem_of = $in_mem_of;
$note = $note;
$add_and_cancel = $add_and_cancel;
$add_and_repeat = $add_and_repeat;
$cancel = $cancel;
$undo = $undo;
$year_num = $year_num;
$force_log = $force_log;
$cross_id = $cross_id;
//
error_reporting(E_ALL);
//
if (isset($amount)) $amount = kix\k::Safe($amount,kix\k::PhpValueOf_safe_hint_type("REAL_NUM"));
if (isset($day_num)) $day_num = kix\k::Safe($day_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($email_address)) $email_address = kix\k::Safe($email_address,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS"));
if (isset($id)) $id = kix\k::Safe($id,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($month_num)) $month_num = kix\k::Safe($month_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($per_clerk_seq_num)) $per_clerk_seq_num = kix\k::Safe($per_clerk_seq_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($year_num)) $year_num = kix\k::Safe($year_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_formattednoteappendage.phtml");
require_once("f_emailaddrofbpn.phtml");
require_once("f_methodselectionlist.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
?>
<html>

<head>
<title>KEYclick - Log old donation</title>
</head>

<?php
if ($cross_id)
   {
   BodyOpen("CurrentOperation.amount");
   }
else
   {
   BodyOpen("CurrentOperation.id");
   }
?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <h6 align="center"><a href="javascript:close();">KEYCLICK SYSTEM</a></h6>
        <h1 align="center">Log old donation</h1>
        <hr>
        <br>
        <?
           $agency = BeValidBoardingPass($db_link,$bpn);
           if ($agency == "")
              {
              KickOff();
              }
           else
              {
              $possible_preemptive_op = 0;
              $feedback_column_width_percentage = 25;
              echo "<table width=100%><tr>"
                 . "<td width=$feedback_column_width_percentage% valign=top bgcolor=#F7F7F7 cellspacing=10>"
                 . "<p><b><u>Previous operation</u></b></p>\n";
              if (($add_and_repeat) || ($add_and_cancel))
                 {
                 //
                 // User indicated that data should be saved.  Validate parameters.
                 //
                 echo "<small>\n";
                 //
                 if (
                       (($id != "") && is_numeric($id))
                    and
                       (($amount != "") && is_numeric($amount))
                    and
                       ((trim($email_address == "") || filter_var($email_address,FILTER_VALIDATE_EMAIL)))
                    )
                 // then
                    {
                    $valid_id = 0;
                    //
                    // Lookup the resident record with the specified id.
                    //
                    $result = $db_link->query
                       (
                       "select resident_base.name"
                       . " , concat(house_num,' ',street.name) as address1"
                       . " , city.name as city"
                       . " , state.abbreviation as state"
                       . " , null as zip"
                       . " , agency as this_rod_agency"
                       . " from resident_base"
                         . " join street on (street.id=resident_base.street_id)"
                         . " join city on (city.id=street.city_id)"
                         . " join state on (state.id=city.state_id)"
                       . " where resident_base.id='$id'"
                       )
                       or die("Master record lookup failed with error: " . mysqli_error($db_link));
                    if (mysqli_num_rows($result))
                       {
                       extract(mysqli_fetch_array($result));  //Sets $name,$address1,$city,$state,$zip
                       $valid_id = 'TRUE';
                       }
                    else
                       {
                       $result = $db_link->query
                          (
                          "select name"
                          . " , address1"
                          . " , city"
                          . " , state"
                          . " , zip"
                          . " , agency as this_rod_agency"
                          . " from resident_journal"
                          . " where id='$id'"
                          . " order by timestamp desc"
                          . " limit 1"
                          );
                       if (mysqli_num_rows($result))
                          {
                          extract(mysqli_fetch_array($result));  //Sets $name,$address1,$city,$state,$zip
                          $valid_id = 'TRUE';
                          }
                       }
                    if (!$valid_id)
                       {
                       echo "<p><b>FAILED</b></p>\n"
                          . "<p><b>Invalid ROD#.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the "
                          . "problem.</b></p>\n";
                       }
                    else
                       {
                       //
                       // Supply missing date parts
                       //
                       if (!$month_num) $month_num = 1;
                       if (!$day_num) $day_num = 1;
                       //
                       if (!$force_log)
                          {
                          //
                          // We have not investigated the possibility that a preemptive operation has made this submission
                          // stale.  Check for updates made since the date of this donation.  Such updates might obsolete the
                          // donation data.
                          //
                          $result = $db_link->query
                             (
                             "select op as possible_preemptive_op from resident_journal "
                             . "where id='$id' "
                             . "   and timestamp > '$year_num-$month_num-$day_num' "
                             . "   and op = 'UPDATE' "
                             . "order by timestamp desc "
                             . "limit 1 "
                             )
                             or die("Check for preemptive op failed with error: " . mysqli_errno($db_link));
                          if (mysqli_num_rows($result)) extract(mysqli_fetch_array($result));  //Sets $possible_preemptive_op
                          }
                       //
                       if (!$possible_preemptive_op)
                          {
                          //
                          // Make sure the specified ROD # belongs to the user's agency.
                          //
                          if ($this_rod_agency == $agency)
                             {
                             //
                             // Determine next value for per_clerk_seq_num.
                             //
                             $per_clerk_seq_num = 1;
                             extract
                                (
                                mysqli_fetch_array
                                   (
                                   $db_link->query
                                      (
                                      "select ifnull(max(per_clerk_seq_num)+1,1) as per_clerk_seq_num from donation "
                                      . " where entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                                      )
                                   )
                                );
                             //
                             // Check for prior donations.
                             //
                             $num_priors = "";
                             $result = $db_link->query("select count(*) as num_priors from donation where id=$id")
                                or die("Check for priors failed with error: " . mysqli_error($db_link));
                             extract(mysqli_fetch_array($result));
                             //
                             $db_link->query
                                ($qry =
                                "insert into donation "
                                .  "set id=$id "
                                .  "   , date='$year_num-$month_num-$day_num' "
                                .  "   , amount=$amount "
                                .  "   , be_interested_in_patient_care=" . ($be_interested_in_patient_care ? "TRUE" : "FALSE")
                                .  "   , be_interested_in_support=" . ($be_interested_in_support ? "TRUE" : "FALSE")
                                .  "   , be_interested_in_volunteering=" . ($be_interested_in_volunteering ? "TRUE" : "FALSE")
                                .  "   , be_interested_in_bequesting=" . ($be_interested_in_bequesting ? "TRUE" : "FALSE")
                                .  "   , method='$method' "
                                .  "   , in_mem_of='" . addslashes(trim($in_mem_of)) . "' "
                                .  "   , note='" . addslashes(trim($note)) . "' "
                                .  "   , entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                                .  "   , per_clerk_seq_num=$per_clerk_seq_num "
                                )
                                or die("Insert failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                             $db_link->query($qry = "update resident_base set year_of_last_appeal_to_become_a_donor = null where id = '$id'")
                                or die("Update failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                             $db_link->query($qry = "delete from web_donor where resident_id = '$id'")
                                or die("Replacement of old email address failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                             if (trim($email_address) != "")
                               {
                               $db_link->query
                                  ($qry = "insert ignore web_donor set email_address = '$email_address', resident_id = '$id' on duplicate key update resident_id = '$id'")
                                  or die("Save of email address failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                               }
                             //
                             echo "<table width=100%><tr><td><b>SUCCEEDED</b></td>\n"
                                . "<td align=right><form action=form-add-donation.phtml>\n"
                                . "   <input type=hidden name=bpn value=$bpn>\n"
                                . "   <input type=hidden name=per_clerk_seq_num value=$per_clerk_seq_num>\n"
                                . "   <input type=submit name=undo value=Undo></form></td></tr></table>\n"
                                . "<small><dl>\n"
                                . "<dt>ROD#:</dt><dd>$id</dd>\n"
                                . "<dt>Lookup data:</dt>\n"
                                . "   <dd>\n"
                                . "      <a href=form-act-singly.phtml?bpn=$bpn&id=$id>"
                                . "         $name<br>$address1<br>$city $state<br>$email_address\n"
                                . "      </a>\n"
                                . "   </dd>\n";
                             if ($num_priors)
                                {
                                echo "<hr><a href=form-act-singly.phtml?bpn=$bpn&id=$id>$num_priors prior donation(s)</a> "
                                   . "on record\n";
                                }
                             echo "<dt>Date:</dt><dd>$year_num-$month_num-$day_num</dd>\n"
                                . "<dt>Amount:</dt><dd>\$$amount</dd>\n"
                                . "<dt>Interested in patient care:</dt><dd>" . ($be_interested_in_patient_care ? "YES" : "no") . "&nbsp;</dd>\n"
                                . "<dt>Interested in support:</dt><dd>" . ($be_interested_in_support ? "YES" : "no") . "&nbsp;</dd>\n"
                                . "<dt>Interested in volunteering:</dt><dd>" . ($be_interested_in_volunteering ? "YES" : "no") . "&nbsp;</dd>\n"
                                . "<dt>Interested in bequesting:</dt><dd>" . ($be_interested_in_bequesting ? "YES" : "no") . "&nbsp;</dd>\n"
                                . "<dt>Method:</dt><dd>$method</dd>\n"
                                . "<dt>In memory of:</dt><dd>$in_mem_of&nbsp;</dd>\n"
                                . "<dt>Note:</dt><dd>$note&nbsp;</dd>\n"
                                . "</dl>\n"
                                . "<br/>\n"
                                . "<form action='../" . $ini[app][superapp] . "/protected/donation_ack_letter.aspx' method=post>\n"
                                .   "<input type=hidden name=agency value='$agency'>\n"
                                .   "<input type=hidden name=donor_name value='$name'>\n"
                                .   "<input type=hidden name=address value='$address1'>\n"
                                .   "<input type=hidden name=city value='$city'>\n"
                                .   "<input type=hidden name=state value='$state'>\n"
                                .   "<input type=hidden name=amount value='$amount'>\n"
                                .   "<input type=hidden name=date value='$year_num-$month_num-$day_num'>\n"
                                .   "<input type=submit name=donation_ack_letter value='Gen ack letter'>\n"
                                . "</form>\n";
                             if (trim($email_address) != "")
                                {
                                echo "<br/>\n"
                                   . "<form action='../" . $ini[app][superapp] . "/protected/donation_ack_email_trigger.aspx' method=post>\n"
                                   .   "<input type=hidden name=agency value='$agency'>\n"
                                   .   "<input type=hidden name=member_email_address value='" . EmailAddrOfBpn($db_link,$bpn) . "'>\n"
                                   .   "<input type=hidden name=donor_name value='$name'>\n"
                                   .   "<input type=hidden name=amount value='$amount'>\n"
                                   .   "<input type=hidden name=date value='$year_num-$month_num-$day_num'>\n"
                                   .   "<input type=hidden name=donor_email_address value='$email_address'>\n"
                                   .   "<input type=submit name=donation_ack_email value='Gen ack email'>\n"
                                   . "</form>\n";
                                }
                             echo "</small>\n";
                             }
                          else
                             {
                             echo "<p><b>FAILED</b></p>\n"
                                . "<p><b>The specified ROD # is not associated with your agency.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the "
                                . "problem.</b></p>\n";
                             }
                          }  // the donation record wasn't stale
                       else
                          {
                          //
                          // the donation record may be stale
                          //
                          echo "<p><b><font color=#ff9900>SUSPENDED</font></b></p>\n"
                             . "<p><b>ROD record $id has been $possible_preemptive_op";
                          //
                          // Cast the op word into the past tense.
                          //
                          switch ($possible_preemptive_op)
                             {
                             case "INSERT":
                                echo "ED";
                                break;
                             case "UPDATE":
                             case "DELETE":
                                echo "D";
                                break;
                             }
                          echo " since the specified donation date.&nbsp The donation data you entered may be stale.</b></p>\n";
                          }
                       }  // the parameters were valid
                    }  // the specified ID was valid
                 else
                    {
                    echo "<p><b>FAILED</b></p>\n"
                       . "<p><b>One or more fields were missing or invalid.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the "
                       . "problem.</b></p>\n";
                    }
                 //
                 echo "</small>\n";
                 //
                 }
              elseif ($undo)
                 {
                 $db_link->query
                    (
                    "delete from donation "
                    . "where entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                    . "   and per_clerk_seq_num=$per_clerk_seq_num "
                    )
                    or die("Undo failed with error: " . mysqli_error($db_link));
                 //
                 echo "<p><b>UNDONE</b></p>\n";
                 }
              else
                 {
                 echo "<p>None</p>\n";
                 }
              //
              echo "</td><td width=5%>&nbsp;</td><td valign=top>\n";
              //
              if (!$possible_preemptive_op)
                 {
                 //
                 $id = $name = $address1 = $city = $state = $zip = $amount = $be_interested_in_patient_care = $be_interested_in_support = $be_interested_in_volunteering =
                    $be_interested_in_bequesting = $method = $in_mem_of = $note = $email_address = "";
                 //
                 // On first time in, must set $year_num to something, else it's possible to insert date 0000-00-00.
                 //
                 if (!$year_num) $year_num = date('Y');
                 //
                 if ((!$add_and_cancel) && (!$cancel))
                    {
                    echo "<p><b><u>Current operation:</u></b></p>\n"
                       . "<form name=CurrentOperation action=form-add-donation-old.phtml method=post>\n"
                       . "   <input type=hidden name=bpn value=$bpn>\n"
                       . "   <table>\n"
                       . "      <tr>\n"
                       . "         <td align=right>Approximate date:</td>\n"
                       . "         <td colspan=2>\n"
                       . "            <table>\n"
                       . "               <tr><td colspan=3><hr></td></tr>\n"
                       . "               <tr>\n"
                       . "                  <td align=center>Year</td><td align=center>Month</td><td align=center>Day</td>\n"
                       . "               </tr>\n"
                       . "               <tr>\n"
                       . "                  <td align=center>\n"
                       . "                     <select name=year_num>\n"
                       . "               <option selected>$year_num</option>\n";
                    for ($year_num_index = date('Y'); $year_num_index >= 1951; $year_num_index--)
                       {
                       echo "<option>$year_num_index</option>\n";
                       }
                    echo "                     </select>\n"
                       . "                  </td>\n"
                       . "                  <td align=center>\n"
                       . "                     <select name=month_num>\n"
                       . "               <option selected>$month_num</option>\n"
                       . "               <option></option>";
                    for ($month_num_index = 1; $month_num_index <= 12; $month_num_index++)
                       {
                       echo "<option>$month_num_index</option>\n";
                       }
                    echo "                     </select>\n"
                       . "                  </td>\n"
                       . "                  <td align=center>\n"
                       . "                     <select name=day_num>\n"
                       . "               <option selected>$day_num</option>\n"
                       . "               <option></option>";
                    for ($day_num_index = 1; $day_num_index <= 31; $day_num_index++)
                       {
                       echo "<option>$day_num_index</option>\n";
                       }
                    echo "                     </select>\n"
                       . "                  </td>\n"
                       . "               </tr>\n"
                       . "               <tr><td colspan=3 align=center>(Choose blank or arbitrary value if unknown.)</td></tr>\n"
                       . "               <tr><td colspan=3><hr></td></tr>\n"
                       . "            </table>\n"
                       . "         </td>\n"
                       . "      </tr>\n"
                       . "      <tr><td align=right>ROD #:</td><td colspan=2><input type=text name=id size=6 maxlength=6 value=$cross_id></td></tr>\n"
                       . "      <tr><td align=right>Amount: $</td><td colspan=2><input type=text name=amount size=6 maxlength=10></td></tr>\n"
                       . "      <tr><td align=right>Interested in patient care: </td><td colspan=2><input type=checkbox name=be_interested_in_patient_care></td></tr>\n"
                       . "      <tr><td align=right>Interested in support: </td><td colspan=2><input type=checkbox name=be_interested_in_support></td></tr>\n"
                       . "      <tr><td align=right>Interested in volunteering: </td><td colspan=2><input type=checkbox name=be_interested_in_volunteering></td></tr>\n"
                       . "      <tr><td align=right>Interested in bequesting: </td><td colspan=2><input type=checkbox name=be_interested_in_bequesting></td></tr>\n"
                       . "      <tr><td align=right>Received via:</td><td colspan=2>\n";
                    echo MethodSelectionList($db_link,$agency);
                    echo "      </td></tr>\n"
                       . "      <tr><td align=right>In memory of:</td><td colspan=2><input type=text name=in_mem_of size=60 maxlength=60></td></tr>\n"
                       . "      <tr><td align=right>Email address:</td><td colspan=2><input type=text name=email_address size=60 maxlength=254 value=$cross_email_address></td></tr>\n"
                       . "      <tr><td align=right>Note:</td><td colspan=2><textarea name=note cols=40 rows=4 wrap></textarea></td></tr>\n"
                       . "      <tr>\n"
                       . "         <td colspan=2>\n"
                       . "            <table width=100%>\n"
                       . "               <tr>\n"
                       . "                  <td align=center><input type=submit name=add_and_repeat value=\"Add and Repeat\"></td>\n"
                       . "                  <td align=center><input type=submit name=add_and_cancel value=\"Add and Stop\"></td>\n"
                       . "                  <td align=center><input type=submit name=cancel value=Cancel></td>\n"
                       . "               </tr>\n"
                       . "            </table>\n"
                       . "         </td>\n"
                       . "      </tr>\n"
                       . "   </table>\n"
                       . "</form>\n";
                    $cross_id = $cross_email_address = "";
                    }  // user wants to enter another old donation
                 else
                    {
                    echo "<p><b><a href=\"javascript:close();\">Go to <b>Main KEYclick</b> page.</a></b></p>\n";
                    }
                 }  // no danger of stale donation data
              else
                 {
                 //
                 // donation data might be stale
                 //
                 echo "<p><b>KEYclick needs some advice on how to proceed.</b></p>\n"
                    . "<p>ROD record $id currently holds:</p>\n"
                    . "<blockquote>\n"
                    . "   $name<br>$address1<br>$city $state $zip\n"
                    . "</blockquote>\n"
                    . "<br/>\n"
                    . "<table>\n"
                    . "<tr><td>\n"
                    . "   <form action=form-add-donation-old.phtml method=post>"
                    . "      <input type=hidden name=bpn value=$bpn>\n"
                    . "      <input type=hidden name=year_num value=$year_num>\n"
                    . "      <input type=hidden name=month_num value=$month_num>\n"
                    . "      <input type=hidden name=day_num value=$day_num>\n"
                    . "      <input type=hidden name=id value=$id>\n"
                    . "      <input type=hidden name=amount value=$amount>\n"
                    . "      <input type=hidden name=be_interested_in_patient_care value=$be_interested_in_patient_care>\n"
                    . "      <input type=hidden name=be_interested_in_support value=$be_interested_in_support>\n"
                    . "      <input type=hidden name=be_interested_in_volunteering value=$be_interested_in_volunteering>\n"
                    . "      <input type=hidden name=be_interested_in_bequesting value=$be_interested_in_bequesting>\n"
                    . "      <input type=hidden name=method value=$method>\n"
                    . "      <input type=hidden name=in_mem_of value=$in_mem_of>\n"
                    . "      <input type=hidden name=email_address value=$email_address>\n"
                    . "      <input type=hidden name=note value=$note>\n"
                    . "      <input type=hidden name=add_and_cancel value=$add_and_cancel>\n"
                    . "      <input type=hidden name=add_and_repeat value=$add_and_repeat>\n"
                    . "      <input type=hidden name=force_log value=TRUE>\n"
                    . "      <input type=submit value=\"CLICK HERE\">\n"
                    . "   </form>\n"
                    . "</td><td nowrap valign=top>...</td>\n"
                    . "<td valign=top>if you are sure that the above person or party is <b>essentially the same</b> as "
                    . "   the person or party whose donation you are now logging.\n"
                    . "</td></tr>\n"
                    . "<tr><td>&nbsp;</td></tr>\n"
                    . "<tr><td>\n"
                    . "   <form action=form-add-resident.phtml method=post>"
                    . "      <input type=hidden name=bpn value=$bpn>\n"
                    . "      <input type=submit value=\"CLICK HERE\">\n"
                    . "   </form>\n"
                    . "</td><td nowrap valign=top>...</td>\n"
                    . "<td valign=top>if the donation you are now logging should be associated with a <b>new ROD "
                    . "   record</b>.\n"
                    . "</td></tr>\n"
                    . "</table>\n";
                 }
              echo "</td></tr></table>\n";
              //
              } // BeValidBoardingPass
        ?>
        <br>
        <p><small><small><em><pre>$Id: form-add-donation-old.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>
