<?
//
// $Id: form-export.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head><title>KEYclick - Export ROD</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <?
           PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"eye-candy",1);
           ?>
        </td><td>
           <h6 align="center">
              <a href="javascript:close();">KEYCLICK SYSTEM</a></h6>
           <h1 align="center">Export ROD</h1>
        </td></tr></table>
        <hr>
        <br>
        <?
           $agency = BeValidBoardingPass($db_link,$bpn);
           if ($agency == "")
              {
              KickOff();
              }
           else
              {
              ?>
              <p>Specify which kind of ROD you want to export:</p>
              <table cellspacing=10>
                 <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top><b><a href=form-export-full.phtml?bpn=<? echo $bpn; ?>>Full</b></a></td><td valign=top>Export the entire ROD, suitable for a <i>total saturation mailout</i>.</td>
                 <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top nowrap><b><a href=form-export-follow-up.phtml?bpn=<? echo $bpn; ?>>Follow-up</b></a></td><td valign=top>This is the full ROD <i>minus</i> records associated with recent donations.&nbsp; This option gives you the chance to define what "recent" means.</td>
              </table>
              <br>
              <hr>
              <?
              }
        ?>
        <br>
        <p><small><small><em><pre>$Id: form-export.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $</pre></em></small></small>
      </td>
    </tr>
  </table>
</body>

</html>
