<?
//
// $Id: form-act-singly.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$save = $save;
//
// Make parameters safe
//
if (isset($email_address)) $email_address = kix\k::Safe($email_address,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS"));
if (isset($house_num)) $house_num = kix\k::Safe($house_num,kix\k::PhpValueOf_safe_hint_type("HYPHENATED_ALPHANUM"));
if (isset($id)) $id = kix\k::Safe($id,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($id_to_save)) $id_to_save = kix\k::Safe($id_to_save,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($name)) $name = kix\k::Safe($name,kix\k::PhpValueOf_safe_hint_type("HUMAN_NAME"));
if (isset($street_id)) $street_id = kix\k::Safe($street_id,kix\k::PhpValueOf_safe_hint_type("NUM"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_formattednoteappendage.phtml");
require_once("f_emailaddrofbpn.phtml");
require_once("f_streetselectionlist.phtml");
require_once("f_cityselectionlist.phtml");
require_once("f_stateselectionlist.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
//
if ($ini[app][do_report_all_errors]) error_reporting(E_ALL);
?>
<html>

<head>
<title>KEYclick - Modify or remove resident record</title>
</head>

<? BodyOpen("CurrentOperation.name"); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <h6 align="center"><a href="javascript:close();">KEYCLICK SYSTEM</a></h6>
        <h1 align="center">Modify or remove resident record</h1>
        <hr>
        <br>
        <?
           if (($agency = BeValidBoardingPass($db_link,$bpn)) == "")
              {
              KickOff();
              }
           else
           {
           //
           // Database is up.
           //
           $feedback_column_width_percentage = 25;
           echo "<table width=100%><tr>"
              . "<td width=$feedback_column_width_percentage% valign=top bgcolor=#F7F7F7 cellspacing=10>"
              . "<p><b><u>Previous operation</u></b></p>\n";
           if ($save)
              {
              //
              // User indicated that data should be saved.  Validate parameters.
              //
              echo "<small>\n";
              //
              if (($action == "update") || ($action == "delete"))
                 {
                 $result = $db_link->query
                    (
                    "select resident_base.name as old_name "
                    .  " , concat(house_num,' ',street.name) as old_address1 "
                    .  " , city.name as old_city "
                    .  " , state.abbreviation as old_state "
                    .  " , null as old_zip "
                    .  " from resident_base "
                       . " join street on (street.id=resident_base.street_id) "
                       . " join city on (city.id=street.city_id) "
                       . " join state on (state.id=city.state_id) "
                    .  " where resident_base.id=$id_to_save "
                    )
                    or die("Select failed with error: " . mysqli_error($db_link));
                 //
                 extract(mysqli_fetch_array($result));
                 }
              if ($action == "update")
                 {
                 if (
                       ($house_num != "")
                    and
                       (($street_id = trim($street_id)) != "")
                    and
                       ((trim($email_address == "") || filter_var($email_address,FILTER_VALIDATE_EMAIL)))
                    )
                 // then
                    {
                    $result = $db_link->query
                       (
                       "update resident_base "
                       .  "set name=NULLIF('" . addslashes(strtoupper(trim($name))) . "','') "
                       .  "   , house_num='" . addslashes($house_num) . "' "
                       .  "   , street_id='" . addslashes($street_id) . "' "
                       .  "where id=$id_to_save "
                       .  "limit 1 "
                       )
                       or die("Update failed with error: " . mysqli_error($db_link));
                    //
                    $db_link->query($qry = "delete from web_donor where resident_id = '$id_to_save'")
                       or die("Replacement of old email address failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                    if (trim($email_address) != "")
                      {
                      $result = $db_link->query
                         ($qry = "insert ignore web_donor set email_address = '$email_address', resident_id = '$id_to_save' on duplicate key update resident_id = '$id_to_save'")
                         or die("Update of email address failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                      }
                    //
                    $result = $db_link->query
                       (
                       "insert into resident_journal "
                       .  "set name='" . addslashes($old_name) . "' "
                       .  "   , address1='" . addslashes($old_address1) . "' "
                       .  "   , city='" . addslashes($old_city) . "' "
                       .  "   , state='" . addslashes($old_state) . "' "
                       .  "   , zip='" . addslashes($old_zip) . "' "
                       .  "   , id=$id_to_save "
                       .  "   , op='UPDATE' "
                       .  "   , user_email_addr='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                       )
                       or die("Journal entry failed with error: " . mysqli_error($db_link));
                    //
                    $result = $db_link->query
                       (
                       "select resident_base.name "
                       .  " , concat(house_num,' ',street.name) as address1 "
                       .  " , city.name as city "
                       .  " , state.abbreviation as state "
                       .  " from resident_base "
                          . " join street on (street.id=resident_base.street_id) "
                          . " join city on (city.id=street.city_id) "
                          . " join state on (state.id=city.state_id) "
                       .  " where resident_base.id=$id_to_save "
                       )
                       or die("Select failed with error: " . mysqli_error($db_link));
                    //
                    extract(mysqli_fetch_array($result));
                    //
                    echo "<p><b>SUCCEEDED</b></p>\n"
                       . "<a href=form-act-singly.phtml?bpn=$bpn&id=$id_to_save><small><dl>\n"
                       . "<dt>Resident ID:</dt><dd>$id_to_save</dd>\n"
                       . "<dt>Name:</dt><dd>$name</dd>\n"
                       . "<dt>Address:</dt><dd>$address1</dd>\n"
                       . "<dt>City:</dt><dd>$city</dd>\n"
                       . "<dt>State:</dt><dd>$state</dd>\n"
                       . "<dt>Email address:</dt><dd>$email_address</dd>\n"
                       . "</dl></small></a>\n";
                    }
                 else
                    {
                    echo "<p><b><u>FAILED</u></b></p>\n"
                       . "<p><b>One or more fields were missing or invalid.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the problem.</b></p>\n";
                    }
                 }
              elseif ($action == "delete")
                 {
                 $result = $db_link->query
                    (
                    "delete from resident_base "
                    .  "where id=$id_to_save "
                    .  "limit 1"
                    )
                    or die("Delete failed with error: " . mysqli_error($db_link));
                 //
                 $result = $db_link->query
                    (
                    "insert into resident_journal "
                    .  "set name='" . addslashes($old_name) . "' "
                    .  "   , address1='" . addslashes($old_address1) . "' "
                    .  "   , city='" . addslashes($old_city) . "' "
                    .  "   , state='" . addslashes($old_state) . "' "
                    .  "   , zip='" . addslashes($old_zip) . "' "
                    .  "   , id=$id_to_save "
                    .  "   , op='DELETE' "
                    .  "   , user_email_addr='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                    )
                    or die("Journal entry failed with error: " . mysqli_error($db_link));
                 //
                 echo "<p><b>SUCCEEDED</b></p>\n"
                    . "<small>Resident ID $id_to_save has been deleted.</small>\n";
                 }
              else
                 {
                 echo "<p><b>FAILED</b></p>\n"
                    . "<p><b>Missing or unknown <u>action</u>.</p>\n";
                 }
              //
              echo "</small>\n";
              //
              $name = $address1 = $city = $state = $zip = $email_address = "";
              //
              }
           else
              {
              echo "<p>None</p>\n";
              }
           //
           echo "</td><td width=5%>&nbsp;</td><td valign=top>\n";
           //
           if ($id != "")
              {
              //
              // Lookup record with specified ID.
              //
              $result = $db_link->query
                 (
                 "select resident_base.name"
                 . " , house_num"
                 . " , street_id"
                 . " , concat(house_num,' ',street.name) as address1"
                 . " , city.name as city"
                 . " , state.abbreviation as state"
                 . " , email_address"
                 . " from resident_base"
                 .   " join street on (street.id=resident_base.street_id)"
                 .   " join city on (city.id=street.city_id)"
                 .   " join state on (state.id=city.state_id)"
                 .   " left join web_donor on (web_donor.resident_id=resident_base.id)"
                 . " where resident_base.id > 0"
                 .   " and resident_base.id = '$id'"
                 .   " and agency = '$agency'"
                 )
                 or die("Query failed with error: " . mysqli_error($db_link));
              $num_rows = mysqli_num_rows($result);
              if ($num_rows)
                 {
                 extract(mysqli_fetch_array($result));
                 //
                 // Retrieve any journal entries associated with this record.
                 //
                 $journal_query_result = $db_link->query
                    (
                    "select *, date_format(timestamp,'%H:%i:%s on %e %b %Y') as timestamp_string "
                    .  "from resident_journal "
                    .  "where id=$id order by timestamp desc"
                    )
                    or die("Journal query failed with error: " . mysqli_error($db_link));
                 $num_journal_rows = mysqli_num_rows($journal_query_result);
                 //
                 // Retrieve any donation entries associated with this record.
                 //
                 $donation_query_result = $db_link->query
                    (
                    "select *, date_format(timestamp,'%H:%i:%s on %e %b %Y') as timestamp_string "
                    .  "from donation "
                    .  "where id=$id order by date desc, timestamp desc"
                    )
                    or die("Donation query failed with error: " . mysqli_error($db_link));
                 $num_donations = mysqli_num_rows($donation_query_result);
                 //
                 echo "<p><b><u>Current operation:</u></b></p>\n"
                    . "<blockquote>\n"
                    . "<form name=CurrentOperation action=form-act-singly.phtml method=post>\n"
                    . "   <input type=hidden name=bpn value=$bpn>\n"
                    . "   <input type=hidden name=id_to_save value=$id>\n";
                 if ($num_journal_rows || $num_donations)
                    {
                    echo "<ul>\n";
                    //
                    if ($num_donations)
                       {
                       extract
                          (
                          mysqli_fetch_array
                             (
                             $db_link->query("select sum(amount) as sum from donation where id=$id group by id")
                             )
                          );
                       echo "<li><a href=#Donations>$num_donations donation"
                          . (($num_donations > 1) ? "s</a> totaling <b>\$$sum</b> are " : "</a> totaling <b>\$$sum</b> is ")
                          . "on file for this record.</li>\n";
                       }
                    //
                    if ($num_journal_rows)
                       {
                       echo "<li><a href=#History>$num_journal_rows journal "
                          . (($num_journal_rows == 1) ? 'entry</a> is ' : 'entries</a> are ' )
                          . "available for this record.</li>\n";
                       }
                    //
                    echo "</ul>\n";
                    }
                 echo "   <table>\n"
                    . "      <tr><td align=right><b>Resident ID:</b></td><td colspan=2><b>$id</b></td></tr>\n"
                    . "      <tr><td align=right>Name:</td><td colspan=2><input type=text name=name value=\"$name\" size=50 maxlength=50></td></tr>\n"
                    . "      <tr><td align=right>House #:</td><td colspan=2><input type=text name=house_num value=\"$house_num\" size=15 maxlength=15></td></tr>\n"
                    . "      <tr><td align=right nowrap=nowrap>Street, City, State:</td><td colspan=2>";
                 StreetSelectionList($db_link,$street_id);
                 echo "</td></tr>\n"
                    . "      <tr><td align=right>Email address:</td><td colspan=2><input type=text name=email_address value=\"$email_address\" size=60 maxlength=254></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td align=right valign=top>Action:</td>\n"
                    . "         <td colspan=2>\n"
                    . "            <label><input type=radio name=action value=update checked>Update</label><br/><br/>\n"
                    . "            <label><input type=radio name=action value=delete>Delete</label><br/><br/>\n"
                    . "            <label><input type=radio name=action value=lognew onclick=\"window.location.href = 'form-add-donation.phtml?bpn=$bpn&cross_id=$id&cross_email_address=$email_address';\">Log a new donation</label><br/><br/>\n"
                    . "            <label><input type=radio name=action value=logold onclick=\"window.location.href = 'form-add-donation-old.phtml?bpn=$bpn&cross_id=$id&cross_email_address=$email_address';\">Log an old donation</label><br/>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "      <tr><td colspan=3><hr></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td colspan=3 align=center>\n"
                    . "            Next Resident ID to modify/remove (optional):\n"
                    . "            <input type=text name=id value=\"\" maxlength=6 size=6>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "      <tr><td colspan=3><hr></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td colspan=3>\n"
                    . "            <table width=100%>\n"
                    . "               <tr>\n"
                    . "                  <td align=center><input type=submit name=save value=Save></td>\n"
                    . "                  <td align=center><input type=submit name=cancel value=Cancel></td>\n"
                    . "               </tr>\n"
                    . "            </table>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "   </table>\n"
                    . "</form>\n";
                 if ($num_donations)
                    {
                    echo "   <a name=Donations></a><p><br><b>Donations totaling \$$sum</b>, in reverse chronological order:</p>\n"
                       . "   <small><ol>\n";
                    for ($i = 1; $i <= $num_donations; $i++)
                       {
                       extract(mysqli_fetch_array($donation_query_result));
                       echo "<li><b>\$$amount on year-month-day $date</b><br>\n"
                          . "<table><tr><td>&nbsp;&nbsp; </td><td>";
                       switch ($method)
                          {
                          case "BIZREPLY":
                             echo "In response to a fund drive appeal;<br>\n";
                             break;
                          case "INMEMOF":
                             echo "In memory of '$in_mem_of';<br>\n";
                             break;
                          case "UNSOLICITED":
                             echo "Unsolicited;<br>\n";
                             break;
                          case "WEB":
                             echo "Via the Internet;<br>\n";
                             break;
                          case "LOVELETTER":
                             echo "In response to a Love Letter;<br>\n";
                             break;
                          case "CREWCARD":
                             echo "Prompted by handing out a Crew Card;<br>\n";
                             break;
                          }
                       if (($method != "INMEMOF") && ($in_mem_of))
                          {
                          echo "Also in memory of '$in_mem_of';<br>\n";
                          }
                       if ($be_interested_in_patient_care)
                          {
                          echo "<b>Interested in volunteering for Patient Care</b>;<br>\n";
                          }
                       if ($be_interested_in_support)
                          {
                          echo "<b>Interested in volunteering for Non-Emergency Support</b>;<br>\n";
                          }
                       if ($be_interested_in_volunteering)
                          {
                          echo "<b>Interested in volunteering</b>;<br>\n";
                          }
                       if ($be_interested_in_bequesting)
                          {
                          echo "<b>Interested in bequesting</b>;<br>\n";
                          }
                       if ($note)
                          {
                          echo "Note:&nbsp; <i>$note</i><br>\n";
                          }
                       echo "<small>(Entered by <a href=mailto:$entered_by><i>$entered_by</i></a> at $timestamp_string).</small><br>"
                          . "<table width=100%>\n"
                          . "   <tr>\n"
                          . "      <td>\n"
                          .        " <table>\n"
                          .          " <tr>\n"
                          .            " <td>\n"
                          .      "         <form action=form-edit-donation.phtml method=post>\n"
                          .      "            <input type=hidden name=bpn value=$bpn>\n"
                          .      "            <input type=hidden name=cross_entered_by value=$entered_by>\n"
                          .      "            <input type=hidden name=cross_per_clerk_seq_num value=$per_clerk_seq_num>\n"
                          .      "            <input type=hidden name=cross_id value=$id>\n"
                          .      "            <input type=hidden name=cross_name value=\"$name\">\n"
                          .      "            <input type=hidden name=cross_address value=\"$address1\">\n"
                          .      "            <input type=hidden name=cross_city value=\"$city\">\n"
                          .      "            <input type=hidden name=cross_state value=\"$state\">\n"
                          .      "            <input type=hidden name=cross_zip value=\"$zip\">\n"
                          .      "            <input type=hidden name=cross_date value=$date>\n"
                          .      "            <input type=hidden name=cross_amount value=$amount>\n"
                          .      "            <input type=hidden name=cross_be_interested_in_patient_care value=$be_interested_in_patient_care>\n"
                          .      "            <input type=hidden name=cross_be_interested_in_support value=$be_interested_in_support>\n"
                          .      "            <input type=hidden name=cross_be_interested_in_volunteering value=$be_interested_in_volunteering>\n"
                          .      "            <input type=hidden name=cross_be_interested_in_bequesting value=$be_interested_in_bequesting>\n"
                          .      "            <input type=hidden name=cross_in_mem_of value=\"$in_mem_of\">\n"
                          .      "            <input type=hidden name=cross_method value=$method>\n"
                          .      "            <input type=hidden name=cross_note value=\"$note\">\n"
                          .      "            <input type=submit name=edit value=\"Edit above entry\">\n"
                          .      "         </form>\n"
                          .            " </td>\n"
                          .            " <td>&nbsp;&nbsp;&nbsp;</td>\n"
                          .            " <td>\n"
                          .              "<form action='../" . $ini[app][superapp] . "/protected/donation_ack_letter.aspx' method=post>\n"
                          .                "<input type=hidden name=agency value='$agency'>\n"
                          .                "<input type=hidden name=donor_name value='$name'>\n"
                          .                "<input type=hidden name=address value='$address1'>\n"
                          .                "<input type=hidden name=city value='$city'>\n"
                          .                "<input type=hidden name=state value='$state'>\n"
                          .                "<input type=hidden name=amount value='$amount'>\n"
                          .                "<input type=hidden name=date value='$date'>\n"
                          .                "<input type=submit name=donation_ack_letter value='Gen ack letter'>\n"
                          .              "</form>\n";
                       if (trim($email_address) != "")
                          {
                          echo "</td>\n"
                             . "<td>&nbsp;&nbsp;&nbsp;</td>\n"
                             . "<td>\n"
                             .   "<form action='../" . $ini[app][superapp] . "/protected/donation_ack_email_trigger.aspx' method=post>\n"
                             .     "<input type=hidden name=agency value='$agency'>\n"
                             .     "<input type=hidden name=member_email_address value='" . EmailAddrOfBpn($db_link,$bpn) . "'>\n"
                             .     "<input type=hidden name=donor_name value='$name'>\n"
                             .     "<input type=hidden name=amount value='$amount'>\n"
                             .     "<input type=hidden name=date value='$date'>\n"
                             .     "<input type=hidden name=donor_email_address value='$email_address'>\n"
                             .     "<input type=submit name=donation_ack_email value='Gen ack email'>\n"
                             .   "</form>\n";
                          }
                       echo             "</td>\n"
                          .          " </tr>\n"
                          .        " </table>\n"
                          . "      </td>\n"
                          . "   </tr>\n"
                          . "</table>\n"
                          . "<hr></td></tr></table>\n";
                       }
                    echo "   </ol></small>\n";
                    }
                 if ($num_journal_rows)
                    {
                    echo "   <a name=History></a><p><br><b>Journal entries</b> in reverse chronological order:</p>\n"
                       . "   <small><ol>\n";
                    for ($i = 1; $i <= $num_journal_rows; $i++)
                       {
                       extract(mysqli_fetch_array($journal_query_result));
                       echo "<li><p>\n";
                       switch ($op)
                          {
                          case "INSERT":
                             echo "Was added by <a href=mailto:$user_email_addr><i>$user_email_addr</i></a> ";
                             break;
                          case "UPDATE":
                             echo "Was:<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$name<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$address1<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$city $state $zip<br>\n";
                             echo "before <a href=mailto:$user_email_addr><i>$user_email_addr</i></a> updated it ";
                             break;
                          case "DELETE":
                             echo "Was:<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$name<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$address1<br>\n"
                                . "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$city $state $zip<br>\n";
                             echo "before <a href=mailto:$user_email_addr><i>$user_email_addr</i></a> deleted it ";
                             break;
                          }
                       echo "at $timestamp_string.</p></li>\n";
                       }
                    echo "   </ol></small>\n";
                    }
                 echo "</blockquote>\n";
                 }
              else
                 {
                 ?>
                 <p><b>No such Resident ID found in association with your agency.</b></p>
                 <blockquote>
                    <form action=form-act-singly.phtml method=post>
                       Edit and retry:
                       <input type=hidden name=bpn value=<? echo $bpn; ?>>
                       <input type=text name=id maxlength=6 size=6 value=<? echo $id; ?>>
                       <input type=submit value="Go!">
                    </form>
                 </blockquote>
                 <?
                 }
              } // non-null $id
           else
              {
              //
              // No ID specified.
              //
              echo "<p><b>No Resident ID specified</b></p>\n"
                 . "<blockquote>\n"
                 . "   <form action=form-act-singly.phtml method=post>\n"
                 . "      <input type=hidden name=bpn value=$bpn>\n"
                 . "      Specify a Resident ID:\n"
                 . "      <input type=text name=id maxlength=6 size=6 value=$id>\n"
                 . "      <input type=submit value=\"Go!\"><br>\n"
                 . "      <br>\n"
                 . "      -- or --<br>\n"
                 . "      <br>\n"
                 . "      <a href=form-add-donation.phtml?bpn=$bpn>Go to <b>Log a NEW donation</b> page.</a><br>\n"
                 . "      <br>\n"
                 . "      -- or --<br>\n"
                 . "      <br>\n"
                 . "      <a href=form-add-donation-old.phtml?bpn=$bpn>Go to <b>Log an OLD donation</b> page.</a><br>\n"
                 . "      <br>\n"
                 . "      -- or --<br>\n"
                 . "      <br>\n"
                 . "      <a href=\"javascript:close();\">Go to <b>Main KEYclick</b> page.</a>\n"
                 . "   </form>\n"
                 . "</blockquote>\n";
              }
           //
           echo "</td></tr></table>\n";
           //
           } // BeValidBoardingPass
        ?>
        <br>
        <p><small><small><em><pre>$Id: form-act-singly.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>
