<?php
//
// $Id$
//
error_reporting(E_ALL);
//
require_once("f_runmode.phtml");
$mode = "";
//
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_serverstatus.phtml");
require_once("f_connectselectdb.phtml");
//
$connected = (ConnectSelectDbInstanceUNPUBLISHED($db_link) == "TRUE");
//
$border_thickness = 0;  //($mode != "");
//
?>
<html>

<head><title>KEYclick System</title></head>

<?php BodyOpen("logon.email_addr"); ?>

<div align="center">
   <center>
   <table border="0" width="80%">
      <tr>
         <td width="100%">
            <div align="left">
               <table border="0" cellspacing="0" cellpadding="0">
                  <tr>
                     <td valign=middle>
                        <h1>KEY<i>click</i></h1>
                        <p>&nbsp;</p>
                        <p><small>Customized data management for direct-mail fundraising.</small></p>
                     </td>
                     <td width="20">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                     <td>
                     <?php
                     if ($connected)
                        {
                        PutLibPhotoRandomPlaced("eye-candy",1);
                        $connected = (ConnectSelectDbInstanceUNPUBLISHED($db_link) == "TRUE");                        }
                     else
                        {
                        echo "&nbsp;";
                        }
                     ?>
                     </td>
                  </tr>
               </table>
               <hr>
               <table border=<?php echo $border_thickness; ?> cellspacing=10>
                  <tr>
                     <td valign=top>
                        <small>
                           <p><b>Welcome to KEYclick!</b></p>
                           <?php
                           if ($connected)
                              {
                              echo "<p><a href=" . $mode . "faq.phtml>FAQ</a></p>\n";
                              echo "<p><a href=mailto:\"" . RoleEmailAddress($db_link,"") . "\">Email sysadmin</a></p>\n";
                              }
                           else
                              {
                              //
                              // If all else fails, use a hardcoded email address.
                              //
                              echo "<p><a href=mailto:kevin.lipscomb@kvrs.org>Email sysadmin</a></p>\n";
                              }
                           ?>
                        </small>
                     </td>
                     <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                     <td>
                     <?php
                     //
                     // Connect to the database.
                     //
                     if ($connected)
                        {
                        ?>
                        <p><b>Please log in.</b></p>
                        <form name=logon action=<?php echo $mode; ?>perform-login.phtml method=post>
                           <table border=<?php echo $border_thickness; ?> cellpadding=10>
                              <tr>
                                 <td align=right>Your email address:</td>
                                 <td><input type=text name=email_addr maxlength=60 size=40></td>
                              </tr>
                              <tr>
                                 <td align=right>Which agency?</td>
                                 <td>
                                    <select name=agency>
                                       <option value=KVRS>Kempsville Volunteer Rescue Squad
                                    </select>
                                 </td>
                              </tr>
                              <tr>
                                 <td colspan=2 align=center>
                                    <input type=submit value=Login>
                                 </td>
                              </tr>
                           </table>
                        </form>
                        <?php
                        }
                     else
                        {
                        ?>
                        <b>Sorry...</b>
                        <blockquote>
                           KEYclick's main functions are unavailable because its database is
                           offline.&nbsp; This condition is temporary.&nbsp; Please try again later.
                        </blockquote>
                        <?php
                        }
                     ?>
                     </td>
                  </tr>
               </table>
               <hr>
               <p><small><small><em><pre>$Id$</pre></em></small></small>
            </div>
         </td>
      </tr>
   </table>
   </center>
</div>

</body>

</html>
