<?
//
// $Id$
//
error_reporting(E_ALL);
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_password.phtml");
require_once("f_serverstatus.phtml");
require_once("f_connectselectdb.phtml");
//
$connected = (ConnectSelectDb("localhost","kalipso",Password(),"keyclick") == "TRUE");
?>
<html>

<head><title>KEYclick System</title></head>

<? BodyOpen(); ?>

<div align="center">
   <center>
   <table border="0" width="80%">
      <tr>
         <td width="100%">
            <div align="left">
               <table border="0" cellspacing="0" cellpadding="0">
                  <tr>
                     <td valign=middle>
                        <h1>KEY<i>click</i></h1>
                        <p>&nbsp;</p>
                        <p><small>Customized data management for direct-mail fundraising.</small></p>
                     </td>
                     <td width="20">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                     <td>
                     <?
                     if ($connected)
                        {
                        PutLibPhotoRandomPlaced("eye-candy",1);
                        }
                     else
                        {
                        echo "&nbsp;";
                        }
                     ?>
                     </td>
                  </tr>
               </table>
               <hr>
               <table cellspacing=10>
                  <tr>
                     <td colspan=5><h3>Actions</h3></td>
                  </tr>
                  <?
                  //
                  // Connect to the database.
                  //
                  if ($connected)
                     {
                     ?>
                     <tr>
                        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                        <td align=right valign=top><b><font color=D0D0D0>Log</font></b></td><td valign=top>a resident's donation.</td>
                        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                        <td rowspan=3 valign=top>
                           <p><i><small>Server status: <? echo ServerStatus(); ?></small></i></p>
                        </td>
                     </tr>
                     <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top><b><font color=D0D0D0>Add</form></b></td><td valign=top>a new resident.</td></tr>
                     <tr>
                        <form action=<? echo $mode; ?>form-act-singly.phtml method=post>
                           <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                           <td align=right valign=middle><b><a href=<? echo $mode; ?>form-act-singly.phtml>Modify or remove</a></b></td>
                           <td valign=middle nowrap>Resident ID # <input type=text name=id maxlength=5 size=5><input type=submit value="Go!"></td>
                        </form>
                     </tr>
                     <?
                     }
                  else
                     {
                     ?>
                     <tr>
                        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                        <td align=right valign=top><b>Sorry...</b></td><td valign=top>KEYclick's main functions are unavailable because its database is
                           offline.&nbsp; This condition is temporary.&nbsp; Please try again later.</td>
                        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                        <td valign=top>
                           <p><i><small>Server&nbsp;status:<br><b>DB OFFLINE</b></small></i></p>
                        </td>
                     </tr>
                     <?
                     }
                  ?>
                  <tr><td colspan=5><h3><br>Administrivia</h3></td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top><b><a href=<? echo $mode; ?>whats-new.phtml>Catch up</a></b></td><td valign=top>on what's new.</td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top>
                  <?
                  if ($connected)
                     {
                     echo "<b><font color=D0D0D0>Modify</font></b></td><td valign=top>system settings (KEYclick Authorities only).";
                     }
                  else
                     {
                     echo "<b>Modify</b></td><td valign=top><b>UNAVAILABLE</b>";
                     }
                  ?>
                  </td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top>
                  <?
                  if ($connected)
                     {
                     echo "<b><a href=" . $mode . "faq.phtml>FAQ</a></b></td><td valign=top>Answers to frequently asked questions.";
                     }
                  else
                     {
                     echo "<b>FAQ</b></td><td valign=top><b>UNAVAILABLE</b>";
                     }
                  ?>
                  </td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top>
                  <?
                  if ($connected)
                     {
                     echo "<b><a href=mailto:\"" . RoleEmailAddress("") . "\">";
                     }
                  else
                     {
                     //
                     // If all else fails, use a hardcoded email address.
                     //
                     echo "<b><a href=mailto:kevin.lipscomb@kvrs.org>";
                     }
                  ?>
                  Contact</a></b></td><td valign=top>the KEYclick System Administrator.</td></tr>
               </table>
               <hr>
               <p><small><small><em><pre>$Id$</pre></em></small></small>
            </div>
         </td>
      </tr>
   </table>
   </center>
</div>

</body>

</html>
