<?
//
// $Id: main.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
$bpn = $bpn;
//
error_reporting(E_ALL);
//
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_serverstatus.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_numrecsinrod.phtml");
require_once("f_numdonationsthiscycle.phtml");
require_once("f_amtdonationsthiscycle.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
$dbkalipso_link = DbkalipsoLink($ini);
//
$border_thickness = 0;
//
?>
<html>

<head><title>KEYclick System</title></head>

<? BodyOpen(); ?>

<div align="center">
   <center>
   <table border="0" width="80%">
      <tr>
         <td width="100%">
            <div align="left">
               <table border="0" cellspacing="0" cellpadding="0">
                  <tr>
                     <td valign=middle>
                        <h1>KEY<i>click</i></h1>
                        <p>&nbsp;</p>
                        <p><small>Customized data management for direct-mail fundraising.</small></p>
                     </td>
                     <td width="20">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                     <td>
                     <?
                     if ($connected)
                        {
                        PutLibPhotoRandomPlaced($ini,$dbkalipso_link,"eye-candy",1);
                        }
                     else
                        {
                        echo "&nbsp;";
                        }
                     ?>
                     </td>
                  </tr>
               </table>
               <hr>
               <table border=<? echo $border_thickness; ?> cellspacing=10>
                  <tr>
                     <td colspan=5><h3>Actions</h3></td>
                  </tr>
                  <?
                     $agency = BeValidBoardingPass($db_link,$bpn);
                     $be_valid_boarding_pass = ($agency != "");
                     if (!$be_valid_boarding_pass)
                        {
                        echo "<tr>\n"
                           . "   <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>\n"
                           . "   <td colspan=4>\n"
                           . "      <table border=1><tr><td>\n";
                        KickOff();
                        echo "      </td></tr></table>\n"
                           . "   </td>\n"
                           . "</tr>\n";
                        }
                     else
                        {
                        // Log action
                        ?>
                        <tr>
                           <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                           <td align=right><b><a href=form-add-donation.phtml?bpn=<? echo $bpn; ?>>Log</a></b></td><td><table border=<? echo $border_thickness; ?>><tr><td>a new donation - <small><i><a href=form-add-donation-old.phtml?bpn=<? echo $bpn; ?>>or log an old one</a></i></small>.</td></tr></table></td>
                           <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                           <td rowspan=6 valign=top>
                              <p><i><small>Server status: <? echo ServerStatus($db_link); ?></small></i></p>
                              <table bgcolor=#E8E8E8>
                                 <tr><td colspan=2><small><u>Summary</u></small></td></tr>
                                 <tr>
                                    <td><small># ROD records:</small></td>
                                    <td align=right><small><?php echo number_format(NumRecsInRod($db_link,$agency)); ?></small></td>
                                 </tr>
                              </table>
                           </td>
                        </tr>
                        <?
                        // Find action
                        ?>
                        <tr>
                           <form action=analyze.phtml method=post>
                              <input type=hidden name=bpn value=<? echo $bpn; ?>>
                              <input type=hidden name=format value=html>
                              <input type=hidden name=algorithm value=FNDNAMADR>
                              <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                              <td align=right><b>Find</b></td>
                              <td><table border=<? echo $border_thickness; ?>><tr><td>by name or address:</td><td><input type=text name=search_text maxlength=50 size=20><input type=submit value="Go!"></td></tr></table></td>
                           </form>
                        </tr>
                        <?
                        // Add action
                        ?>
                        <tr>
                           <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                           <td align=right><b><a href=form-add-resident.phtml?bpn=<? echo $bpn; ?>>Add</a></b></td>
                           <td><table border=<? echo $border_thickness; ?>><tr><td>a name and address to the ROD (Resident/Occupant Database).</td></tr></table></td>
                        </tr>
                        <?
                        // Modify action
                        ?>
                        <tr>
                           <form action=form-act-singly.phtml method=post>
                              <input type=hidden name=bpn value=<? echo $bpn; ?>>
                              <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                              <td align=right><b><a href=form-act-singly.phtml?bpn=<? echo $bpn; ?>>Modify or remove</a></b></td>
                              <td><table border=<? echo $border_thickness; ?>><tr><td>ROD record #</td><td><input type=text name=id maxlength=6 size=6><input type=submit value="Go!"></td></tr></table></td>
                           </form>
                        </tr>
                        <?
                        // Analyse action
                        ?>
                        <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><a href=form-analyze.phtml?bpn=<? echo $bpn; ?>>Analyze</a></b></td><td><table border=<? echo $border_thickness; ?>><tr><td>data and get reports.</td></tr></table></td></tr>
                        <?
                        // Export action
                        ?>
                        <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><b><a href=form-export.phtml?bpn=<? echo $bpn; ?>>Export</a></b></td><td><table border=<? echo $border_thickness; ?>><tr><td>the ROD for mailing label generation.</td></tr></table></td></tr>
                        <?
                        }
                  ?>
                  <tr><td colspan=5><h3><br>Administrivia</h3></td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top>
                  <?
                  if ($connected)
                     {
                     echo "<b><a href=faq.phtml>FAQ</a></b></td><td valign=top>Answers to frequently asked questions.";
                     }
                  else
                     {
                     echo "<b>FAQ</b></td><td valign=top><b>UNAVAILABLE</b>";
                     }
                  ?>
                  </td></tr>
                  <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right valign=top>
                  <?
                  if ($connected)
                     {
                     echo "<b><a href=mailto:" . RoleEmailAddress($db_link) . ">";
                     }
                  else
                     {
                     //
                     // If all else fails, use a hardcoded email address.
                     //
                     echo "<b><a href=mailto:kevin.lipscomb@kvrs.org>";
                     }
                  ?>
                  Contact</a></b></td><td valign=top>the KEYclick System Administrator.</td></tr>
               </table>
               <hr>
               <p><small><small><em><pre>$Id: main.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $</pre></em></small></small>
            </div>
         </td>
      </tr>
   </table>
   </center>
</div>

</body>

</html>
