<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = "";
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
//
if (RunMode($PHP_SELF)) error_reporting(E_ALL);
//
$foundation_dir = "../../foundation";
$pear_dir = "../../pear";
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_beauthorized.phtml");
require_once("f_keyclickmailheaders.phtml");
require_once("$foundation_dir/std_style_class.php");
require_once("Mail.php");
require_once("$pear_dir/Mail/mime.php");
?>
<html>

<head>
<title>KEYclick - Boarding Pass Generation</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
         <table><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
            <? PutLibPhotoRandomPlaced("eye-candy",1); ?>
         </td><td>
            <h6 align="center">
               <a href=<? echo HomePageUrl(); ?>>KEYCLICK SYSTEM</a></h6>
            <h1 align="center">Boarding Pass Generation</h1>
         </td></tr></table>
         <hr>
         <br>
         <?
         if (ConnectSelectDbInstanceUNPUBLISHED($db_link) != "TRUE")
            {
            ?>
            <h2><i>Sorry...</i></h2>
            <b>
            <blockquote>
               <? echo "<p>KEYclick's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
            </blockquote>            
            </b>
            <?
            }
         else
            {
            //
            // Database is up.  Validate parameters.
            //
            if (
                  ($email_addr != "")
               and
                  ($agency != "")
               )
            // then
               {
               if (BeAuthorized($db_link,$email_addr,$agency,$mode) != "TRUE")
                  {
                  ?>
                  <h2><i>Sorry...</i></h2>
                  <blockquote>
                     <?
                     echo "<p><a href=mailto:\""
                        . RoleEmailAddress($db_link,"keyclick-coordinator",$mode,$agency)
                        . "\">$agency's KEYclick Coordinator</a> has not enrolled <i>$email_addr</i> in its table of valid "
                        . "KEYclick users.</p>";
                     ?>
                  </blockquote>            
                  <?
                  }
               else
                  {
                  //
                  // Generate the Boarding Pass Number (bpn).
                  //
                  srand((double)microtime()*1000000); 
                  $raw_bpn =  rand();
                  $result = $db_link->query("select md5(\"$raw_bpn\") as bpn")
                     or die("Generation of Boarding Pass Number failed with error: " . mysqli_error($db_link));
                  extract(mysqli_fetch_array($result));
                  //
                  // Calculate the expiration time.
                  //
                  extract(  // Sets $num_minutes
                     mysqli_fetch_array(
                        $db_link->query(
                           "select value as num_minutes from " . $mode . "tuning_parm "
                           . "where name='boarding-pass-valid-minutes' ")));
                  $expiration_time = time() + $num_minutes*60;
                  //
                  // Record the boarding pass attributes in the manifest.
                  //
                  $db_link->query
                     (
                     "insert into " . $mode . "manifest set bpn='$bpn' "
                     .  ", email_addr='$email_addr' "
                     .  ", ip='$REMOTE_ADDR' "
                     .  ", agency='$agency' "
                     .  ", expiration_time=$expiration_time "
                     )
                     or die("Insert failed with error: " . mysqli_error($db_link));
                  //
                  // Generate the challenge message (plain text).
                  //
                  //    0        1         2         3         4         5         6         7
                  //    123456789012345678901234567890123456789012345678901234567890123456789012
                  $challenge_cold = ""
                     . "This is your KEYclick Boarding Pass.  It is only valid on the computer\n"
                     . "from which you logged into KEYclick, and only for the $agency database.\n\n"
                     . "This Boarding Pass will expire when you have not used KEYclick for $num_minutes\n"
                     . "minutes, or when you explicitly log out.\n\n"
                     . "Please click here to continue:\n"
                     . RootUrl()
                     . "/" . $mode . "main.phtml?bpn=$bpn\n\n";
                  //
                  // Add sig lines.
                  //
                  $challenge_cold .=
                       "-- KEYclick\n"
                     . "-- Home page: " . HomePageUrl() . "\n"
                     . "-- Sysadmin: " . RoleEmailAddress($db_link,"",$mode) . "\n";
                  //
                  // Generate an HTML version of the challenge.
                  //
                  $challenge_hot = ""
                     . "<html>\n"
                     . "   <body bgcolor=#ffffff>\n"
                     . "      <font face=arial>\n"
                     . "         <table align=center bgcolor=#99ccff cellpadding=10 width=80%>\n"
                     . "            <tr>\n"
                     . "               <td width=24%>\n"
                     . "                  <p align=center><small><small>$bpn</small></small></p>\n"
                     . "                  <center>\n"
                     . "                     <h6>BOARDING PASS STUB</h6>\n"
                     . "                     <p><font size=+2><b><a href=" . RootUrl() . "/" . $mode . "main.phtml?bpn=$bpn>Click "
                     . "                        here to board KEYclick.</a></b></font></p>\n"
                     . "                     <h6>$email_addr</h6>\n"
                     . "                  </center>\n"
                     . "                  <p align=center><small><small>$bpn</small></small></p>\n"
                     . "               </td>\n"
                     . "               <td width=2%>\n"
                     . "                  <center>\n"
                     . "                     :<br>:<br>:<br>:<br>:<br>:<br>:<br>:<br>:<br>:<br>:<br>:<br>:\n"
                     . "                  </center>\n"
                     . "               </td>\n"
                     . "               <td width=74%>\n"
                     . "                  <p align=center><small><b> --- $bpn ---</b></small></p>\n"
                     . "                  <table width=100%>\n"
                     . "                     <tr>\n"
                     . "                        <td valign=middle><font size=+2><b>KEYclick Boarding Pass</b></font></td>\n"
                     . "                        <td align=right valign=middle>for <b>$email_addr</b></td>\n"
                     . "                     </tr>\n"
                     . "                  </table>\n"
                     . "                  <br>\n"
                     . "                  This Boarding Pass is only valid on the computer from which you logged into "
                     . "                  KEYclick, and only for the $agency database.&nbsp This Boarding Pass will expire "
                     . "                  when you have not used KEYclick for $num_minutes minutes, or when you explicitly "
                     . "                  log out.\n"
                     . "                  <hr>\n"
                     . "                  <small>"
                     . "                     KEYclick&nbsp; * &nbsp;" . HomePageUrl() . "&nbsp; * &nbsp;Sysadmin=<a href=mailto:" . RoleEmailAddress($db_link,"",$mode) . ">" . RoleEmailAddress($db_link,"",$mode) . "</a>"
                     . "                  </small>\n"
                     . "                  <p align=center><small><b> --- $bpn ---</b></small></p>\n"
                     . "               </td>\n"
                     . "            </tr>\n"
                     . "         </table>\n"
                     . "      </font>\n"
                     . "   </body>\n"
                     . "</html>\n";
                  //
                  $headers = array
                     (
                     'To' => $email_addr,
                     'From' => 'KEYclick <' . RoleEmailAddress($db_link,"",$mode) . '>',
                     'Reply-to' => 'KEYclick <' . RoleEmailAddress($db_link,"",$mode) . '>',
                     'Subject' => 'KEYclick Boarding Pass'
                     );
                  //
                  $mail_mime_obj = new Mail_mime();
                  $mail_mime_obj->setTXTBody($challenge_cold);
                  $mail_mime_obj->setHTMLBody($challenge_hot);
                  $mime_message_body = $mail_mime_obj->get();
                  $headers = $mail_mime_obj->headers($headers);
                  $mail_message_obj =& Mail::factory('sendmail');
                  $result = $mail_message_obj->send($email_addr, $headers, $mime_message_body);
                  //
                  // Send the mail.
                  //
                  //$result = mail($email_addr, "KEYclick Boarding Pass", $challenge, KeyclickMailHeaders());
                  //
                  if ($result)
                     {
                     echo "<p>KEYclick has sent a Boarding Pass to <b>$email_addr</b>.</p>";
                     echo "<p><b>Check your email periodically for the Boarding Pass, which contains instructions for completing the "
                        . "log-in process.</b></p>";
                     echo std_style_class::AolEmailClientWarning();
                     }
                  else
                     {
                     //
                     // Fill the page out with a warning and instructions.
                     //
                     ?>
                     <h2><i>Error!</i></h2>
                     <b>
                     <blockquote>
                        <p>KEYclick encountered an internal error while processing your request.&nbsp; Contact the
                           <a href=mailto:"<? echo RoleEmailAddress($db_link,"",$mode); ?>">KEYclick System Administrator</a>.</p>
                     </blockquote>            
                     </b>
                     <?
                     }
                  }
               }
            else
               {
               //
               // Fill the page out with a warning and instructions.
               //
               ?>
               <h2><i>Error!</i></h2>
               <b>
               <blockquote>
                  <p>You did not supply one or more of the required parameters.&nbsp; You must supply values for these fields:</p>
                  <ul>
                     <li><p>Email address</p>
                     <li><p>Agency</p>
                  </ul>
                  <p>Please press your browser's [<--&nbsp;BACK] button to correct the problems.</p>
               </blockquote>            
               </b>
               <?
               }
            } // database up
         ?>
         <br>
         <hr>
         <p><small><small><em><pre>$Id$</pre></em></small></small>
      </td>
   </tr>
</table>
</body>

</html>
