<?
//
// $Id: perform-update-donation.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$be_interested_in_patient_care = $be_interested_in_patient_care;
$be_interested_in_support = $be_interested_in_support;
$be_interested_in_volunteering = $be_interested_in_volunteering;
$be_interested_in_bequesting = $be_interested_in_bequesting;
$save = $save;
$cancel = $cancel;
//
error_reporting(E_ALL);
//
if (isset($amount)) $amount = kix\k::Safe($amount,kix\k::PhpValueOf_safe_hint_type("REAL_NUM"));
if (isset($cross_entered_by)) $cross_entered_by = kix\k::Safe($cross_entered_by,kix\k::PhpValueOf_safe_hint_type("EMAIL_ADDRESS"));
if (isset($cross_per_clerk_seq_num)) $cross_per_clerk_seq_num = kix\k::Safe($cross_per_clerk_seq_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($day_num)) $day_num = kix\k::Safe($day_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($in_mem_of)) $in_mem_of = kix\k::Safe($in_mem_of,kix\k::PhpValueOf_safe_hint_type("PUNCTUATED"));
if (isset($method)) $method = kix\k::Safe($method,kix\k::PhpValueOf_safe_hint_type("ALPHA"));
if (isset($month_num)) $month_num = kix\k::Safe($month_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($note)) $note = kix\k::Safe($note,kix\k::PhpValueOf_safe_hint_type("PUNCTUATED"));
if (isset($per_clerk_seq_num)) $per_clerk_seq_num = kix\k::Safe($per_clerk_seq_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
if (isset($year_num)) $year_num = kix\k::Safe($year_num,kix\k::PhpValueOf_safe_hint_type("NUM"));
//
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_formattednoteappendage.phtml");
require_once("f_emailaddrofbpn.phtml");
require_once("f_methodselectionlist.phtml");
//
$ini = AppSettings();
$db_link = DbLink($ini);
?>
<html>

<head>
<title>KEYclick - Update donation</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <h6 align="center"><a href="javascript:close();">KEYCLICK SYSTEM</a></h6>
        <h1 align="center">Update donation</h1>
        <hr>
        <br>
        <?
           $agency = BeValidBoardingPass($db_link,$bpn);
           if ($agency == "")
              {
              KickOff();
              }
           else
           {
           $feedback_column_width_percentage = 25;
           echo "<table width=100%><tr>"
              . "<td width=$feedback_column_width_percentage% valign=top bgcolor=#F7F7F7 cellspacing=10>"
              . "<p><b><u>Previous operation</u></b></p>\n";
           if ($save)
              {
              //
              // User indicated that data should be saved.  Validate parameters.
              //
              echo "<small>\n";
              //
              if (($amount != "") && is_numeric($amount))
                 {
                 //
                 // Determine next value for per_clerk_seq_num.
                 //
                 $per_clerk_seq_num = 1;
                 extract
                    (
                    mysqli_fetch_array
                       (
                       $db_link->query
                          (
                          "select ifnull(max(per_clerk_seq_num)+1,1) as per_clerk_seq_num from donation "
                          . " where entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                          )
                       )
                    );
                 //
                $db_link->query
                    ($qry =
                    "update donation "
                    .  "set amount=$amount "
                    .  "   , date='" . $year_num . '-' . $month_num . '-' . $day_num . "' "
                    .  "   , be_interested_in_patient_care=" . ($be_interested_in_patient_care ? "TRUE" : "FALSE")
                    .  "   , be_interested_in_support=" . ($be_interested_in_support ? "TRUE" : "FALSE")
                    .  "   , be_interested_in_volunteering=" . ($be_interested_in_volunteering ? "TRUE" : "FALSE")
                    .  "   , be_interested_in_bequesting=" . ($be_interested_in_bequesting ? "TRUE" : "FALSE")
                    .  "   , method='$method' "
                    .  "   , in_mem_of='" . addslashes(trim($in_mem_of)) . "' "
                    .  "   , note='" . addslashes(trim($note)) . "' "
                    .  "   , entered_by='" . EmailAddrOfBpn($db_link,$bpn) . "' "
                    .  "   , per_clerk_seq_num=$per_clerk_seq_num "
                    .  "where entered_by='$cross_entered_by' "
                    .  "   and per_clerk_seq_num=$cross_per_clerk_seq_num "
                    )
                    or die("Update failed with error: " . mysqli_error($db_link) . ".  qry=[$qry]");
                 }
              else
                 {
                 echo "<p><b>FAILED</b></p>\n"
                    . "<p><b>One or more fields were missing or invalid.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the "
                    . "problem.</b></p>\n";
                 }
              //
              echo "<p><b>SUCCEEDED</b></p>\n";
              echo "</small>\n";
              //
              }
           else
              {
              echo "<p>None</p>\n";
              }
           //
           echo "</td><td width=5%>&nbsp;</td><td valign=top>\n";
           echo "<p><b><a href=form-act-singly.phtml?bpn=$bpn&id=$cross_id>Return to parent ROD record.</a></b></p>\n";
           echo "</td></tr></table>\n";
           //
           } // BeValidBoardingPass
        ?>
        <br>
        <p><small><small><em><pre>$Id: perform-update-donation.phtml 7093 2020-05-01 01:00:11Z kevinanlipscomb $</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>
