<?php
//
// $Id$
//
$foundation_dir = "../../foundation";
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("$foundation_dir/std_style_class.php");
?>
<html>

<head><title>KEYclick - What's New</title></head>

<?php BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center"><a href="<?php echo HomePageUrl(); ?>">KEYCLICK SYSTEM</a></h6>
           <h1 align="center">What's New</h1>
        <hr>
        <?php PutLibPhotoRandomPlaced("eye-candy",1,"right"); ?>
        <?php echo std_style_class::CatchUpBlurb(); ?>
        <p><b>2002-07-20:&nbsp; </b>Enhanced Boarding Pass emails by constructing them with PEAR::Mail_Mime package.</p>
        <p><b>2002-07-19:&nbsp; </b>Shaved several unneeded columns from the ROD and revised RODBY* analyses not to refer to
           the shaved-off columns.</p>
        <p><b>2002-07-18:&nbsp; </b>Added a note to the Boarding Pass screen (perform-login script) to warn AOL users about
           a potential log in problem, and its workaround.</p>
        <p><b>2002-07-17:&nbsp; </b>Made export operations much more size and time efficient.&nbsp; Fixed a bug related to
           #580326 (fixed on 2002-07-11) but affecting the logging of old vice new donations.</p>
        <p><b>2002-07-16:&nbsp; </b>Added automatic generation and export of Follow-Up RODs.</p>
        <p><b>2002-07-11:&nbsp; </b>Fixed bug #580326 (Newly-approved users receive fatal error on attempts to log new
           donations).&nbsp; Added unprivileged links to index (front) page.&nbsp; Added donation history to the Modify or
           Remove page.</p>
        <p><b>2002-06-25:&nbsp; </b>Eliminated image from data entry forms.</p>
        <p><b>2002-05-01:&nbsp; </b>Added ability to pull a record from an analysis report directly into the Modify or
           Delete page, all with just one click.&nbsp; Added Find By Name or Address capability.</p>
        <p><b>2002-05-01:&nbsp; </b>Added ability to log old donations.&nbsp; This also makes several new kinds of
           queries possible.</p>
        <p><b>2002-04-28:&nbsp; </b>Improved the Analyze capability to support massively resource-intensive analyses.&nbsp;
           Made View On Screen capability usable.</p>
        <p><b>2002-04-23:&nbsp; </b>Improved the Analyze capability so that KEYclick will present a dynamic menu of
           the analyses that are store in the database for the appropriate agency.&nbsp; This vastly simplifies the
           development of new custom analyses.</p>
        <p><b>2002-04-22:&nbsp; </b>Added very rough Analyze capability, with only one defined query whose output is still
           messy.&nbsp; Had to capture the change, though.</p>
        <p><b>2002-04-20:&nbsp; </b>Added the Log Donation capability.</p>
        <p><b>2002-04-19:&nbsp; </b>Revised the Add action page to accept house/building number, street name, and apartment
           number as distinct fields.&nbsp; This will allow KEYclick to enforce a standard notation.</p>
        <p><b>2002-04-11:&nbsp; </b>Added journaling.  Now all changes to the ROD will be associated with a user, and
           can be easily reversed.</p>
        <p><b>2002-04-09:&nbsp; </b>Implemented privacy/security mechanism (email authentication) and the Export
           capability.</p>
        <p><b>2002-03-12:&nbsp; </b>Implemented Add Resident capability.</p>
        <p><b>2002-03-11:&nbsp; </b>Went live with Modify/Remove Resident capability.</p>
        <p><b>2002-03-11:&nbsp; </b>Began script development.</p>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

