ALTER TABLE `keyclick`.`resident` ADD `state_id` SMALLINT UNSIGNED NOT NULL;  
update resident set state_id=1 where state='VA';
update resident set state_id=3 where state='SC';
update resident set state_id=4 where state='CT';
update resident set state_id=5 where state='NH';
update resident set state_id=6 where state='PA';
ALTER TABLE `resident` DROP `state`;
ALTER TABLE `keyclick`.`resident` ADD `city_id` SMALLINT UNSIGNED NOT NULL;  
update resident set city_id=1 where city='VIRGINIA BEACH';
update resident set city_id=1 where city='VA BEACH';
update resident set city_id=1 where city='VIRGINIA BEACHQ';
update resident set city_id=5 where city='STERLING';
update resident set city_id=6 where city='NORFOLK';
update resident set city_id=7 where city='CHESAPEAKE';
update resident set city_id=8 where city='SUFFOLK';
update resident set city_id=9 where city='ABBEVILLE';
update resident set city_id=10 where city='FALLS CHURCH';
update resident set city_id=11 where city='FAIRFIELD';
update resident set city_id=12 where city='NORTH CONWAY';
update resident set city_id=14 where city='PITTSBURGH';
ALTER TABLE `resident` DROP `city`;
ALTER TABLE `keyclick`.`resident` ADD `zip5_id` SMALLINT UNSIGNED NOT NULL;  
update resident set zip5_id=1 where left(zip,5)='23464'; 
update resident set zip5_id=2 where left(zip,5)='23462'; 
update resident set zip5_id=3 where left(zip,5)='23456'; 
update resident set zip5_id=4 where left(zip,5)='23453'; 
update resident set zip5_id=0 where left(zip,5)='00000'; 
update resident set zip5_id=6 where left(zip,5)='23455'; 
update resident set zip5_id=7 where left(zip,5)='23466'; 
update resident set zip5_id=8 where left(zip,5)='23452'; 
update resident set zip5_id=9 where left(zip,5)='22101'; 
update resident set zip5_id=10 where left(zip,5)='20164'; 
update resident set zip5_id=11 where left(zip,5)='23507'; 
update resident set zip5_id=12 where left(zip,5)='23454'; 
update resident set zip5_id=13 where left(zip,5)='23502'; 
update resident set zip5_id=14 where left(zip,5)='23322'; 
update resident set zip5_id=15 where left(zip,5)='23451'; 
update resident set zip5_id=16 where left(zip,5)='23432'; 
update resident set zip5_id=17 where left(zip,5)='29620'; 
update resident set zip5_id=18 where left(zip,5)='22041'; 
update resident set zip5_id=19 where left(zip,5)='06430'; 
update resident set zip5_id=20 where left(zip,5)='23467'; 
update resident set zip5_id=21 where left(zip,5)='03860'; 
update resident set zip5_id=22 where left(zip,5)='23321'; 
update resident set zip5_id=23 where left(zip,5)='23320'; 
update resident set zip5_id=24 where left(zip,5)='15206'; 
update resident set zip=substring(zip,7);
ALTER TABLE `keyclick`.`resident` CHANGE `zip` `plus4part` CHAR(4) NOT NULL;
ALTER TABLE `keyclick`.`resident` ADD `street_id` MEDIUMINT UNSIGNED NOT NULL;


