<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$bpn = $bpn;
$filename = $filename;
$sql_query = $sql_query;
$format = $format;
$parent_enumeral = $parent_enumeral;
$algorithm = $algorithm;
//
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_password.phtml");
require_once("f_connectselectdb.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_zipdump.phtml");
//
// error_reporting(E_ALL);  // Inappropriate because we're calling externally-authored routines.
//
$connected = (ConnectSelectDb("localhost","kalipso",Password(),"keyclick") == "TRUE");

        if ($connected != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>KEYclick's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
           </blockquote>            
           </b>
           <?
           }
        else
           {
           //
           $agency = BeValidBoardingPass($bpn,$mode);
           if ($agency == "")
              {
              KickOff($mode);
              }
           else
              {
              switch ($format)
                 {
                 case "":
                 case "html":
                    echo "<html>\n"
                       . "   <head><title>KEYclick - Query result</title></head>\n"
                       . "   ";
                    BodyOpen();
                    echo "      <table border=0 cellpadding=0 cellspacing=0 width=80% align=center>\n"
                       . "         <tr>\n"
                       . "            <td>\n"
                       . "               <table>\n"
                       . "                  <tr>\n"
                       . "                     <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>\n"
                       . "                     <td>\n"
                       . "                        ";
                    PutLibPhotoRandomPlaced("eye-candy",1);
                    mysql_select_db('keyclick');
                    echo "                     </td>\n"
                       . "                     <td>\n"
                       . "                        <h6 align=center>\n"
                       . "                           <a href=" . HomePageUrl() . ">KEYCLICK SYSTEM</a>\n"
                       . "                        </h6>\n"
                       . "                        <h1 align=center>Query result</h1>\n"
                       . "                     </td>\n"
                       . "                  </tr>\n"
                       . "               </table>\n"
                       . "               <hr>\n"
                       . "               <br>\n";
                    require_once("f_readdump.phtml");
                    require_once("f_readdump-rodbyaddr0.phtml");
                    require_once("f_readdump-rodbynam0.phtml");
                    require_once("f_readdump-popnamcnt.phtml");
                    require_once("f_readdump-rodfolup0.phtml");
                    //
                    switch ($format)
                       {
                       case "":
                          switch ($algorithm)
                             {
                             case "POPNAMCNT":
                                ReadDump_POPNAMCNT
                                   (
                                   $sql_query,
                                   $bpn,
                                   $mode,
                                   'FALSE'  // for be_viewable_result
                                   );
                                break;
                             case "RODBYADDR0":
                                ReadDump_RODBYADDR0
                                   (
                                   $sql_query,
                                   $bpn,
                                   $mode,
                                   'FALSE'  // for be_viewable_result
                                   );
                                break;
                             case "RODBYNAM0":
                                ReadDump_RODBYNAM0
                                   (
                                   $sql_query,
                                   $bpn,
                                   $mode,
                                   'FALSE'  // for be_viewable_result
                                   );
                                break;
                             case "RODFOLUP0":
                                ReadDump_RODFOLUP0
                                   (
                                   $year_num,$month_num,$day_num,
                                   $bpn,
                                   $mode,
                                   'FALSE'  // for be_viewable_result
                                   );
                                break;
                             default:
                                ReadDump
                                   (
                                   $sql_query,
                                   $bpn,
                                   '1',  // for allow_dynamic_sorting
                                   $mode,
                                   'FALSE'  // for be_viewable_result
                                   );
                                break;
                             }
                          echo "<p>The analysis nicknamed '<b>$parent_enumeral</b>' is complete.</p>\n"
                             . "<p><b>Next</b>, KEYclick will let you view or download the results of this analysis.</p>\n"
                             . "<form action=" . $mode . "form-analyze.phtml method=post>\n"
                             . "   <input type=hidden name=bpn value=$bpn>\n"
                             . "   <input type=hidden name=parent_enumeral_expression value=\"parent_enumeral='$parent_enumeral'\">\n"
                             . "   Click here to &nbsp; <input type=submit value=Proceed>.\n"
                             . "</form>\n";
                          break;
                       case "html":
                          //
                          // Get $chunk_size.
                          //
                          extract  // Implicitly sets $chunk_size
                             (
                             mysql_fetch_array
                                (
                                mysql_query
                                   (
                                   "select value as chunk_size from " . $mode . "tuning_parm "
                                   .  "where name='screen-view-chunk-size' "
                                   )
                                )
                             );
                          //
                          switch ($algorithm)
                             {
                             case "RODBYADDR0":
                                ReadDump_RODBYADDR0($sql_query,$bpn,$mode);
                                break;
                             case "RODBYNAM0":
                                ReadDump_RODBYNAM0($sql_query,$bpn,$mode);
                                break;
                             case "RODBYADDRSV":
                                $sql_query = "select * from " . $mode . "rod_by_addr "
                                   . "limit " . ($part_num - 1)*$chunk_size . ",$chunk_size";
                                ReadDump
                                   (
                                   $sql_query,
                                   $bpn,
                                   '0',  // don't allow_dynamic_sorting
                                   $mode
                                   );
                                break;
                             case "RODBYNAMSV":
                                $sql_query = "select * from " . $mode . "rod_by_name "
                                   . "limit " . ($part_num - 1)*$chunk_size . ",$chunk_size";
                                ReadDump
                                   (
                                   $sql_query,
                                   $bpn,
                                   '0',  // don't allow_dynamic_sorting
                                   $mode
                                   );
                                break;
                             case "FNDNAMADR":
                                //
                                // Replace spaces and stars with the regexp wildcard character.
                                //
                                $parsed_basic_criteria = strtolower(ereg_replace("[[:space:]]+", " ",$search_text));
                                $parsed_basic_criteria = ereg_replace("\*"," ",$parsed_basic_criteria);
                                $parsed_basic_criteria = ereg_replace(" ",".*",$parsed_basic_criteria);
                                //
//special-2010-a-{
//                                $sql_query = "select id "
                                $sql_query = "select id_accidental_2010_a as id"
//special-2010-a-}
                                   . "   , name "
                                   . "   , address1 "
                                   . "   , city "
                                   . "   , state "
                                   . "   , zip "
                                   . "from " . $mode . "resident "
                                   . "where name rlike '$parsed_basic_criteria' "
                                   . "   or address1 rlike '$parsed_basic_criteria' ";
                                //
                                // DON'T break
                                //
                             default:
                                ReadDump
                                   (
                                   $sql_query,
                                   $bpn,
                                   '1',  // do allow_dynamic_sorting
                                   $mode
                                   );
                                break;
                             }
                          break;
                       }
                    echo "               <br>\n"
                       . "               <p><small><small><em><pre>$Id$</pre></em></small></small>\n"
                       . "            </td>\n"
                       . "         </tr>\n"
                       . "      </table>\n"
                       . "   </body>\n"
                       . "</html>\n";
                    break;
                    //
                 case "zip":
                 default:
                    ZipDump($sql_query,$parent_enumeral);
                    break;
                 }
              }
           }
?>