<?
//
// $Id$
//
function AmtDonationsThisCycle
   (
   $agency,
   $mode = ""
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $amt_donations_this_cycle = 0;
   $qry = "select sum(amount) as amt_donations_this_cycle from "
      .  "   keyclick." . $mode . "donation left join keyclick." . $mode . "resident "
      .  "on "
      .  "   keyclick." . $mode . "donation.id = keyclick." . $mode . "resident.id "
      .  "where agency='$agency' "
      .  "   and date > '" . date('Y') . "-05-01' "
      .  "group by agency ";
   $result = mysql_query($qry)
      or die("NumDonationsThisCycle query failed with error:  " . mysql_error());
   if (mysql_num_rows($result)) extract(mysql_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return $amt_donations_this_cycle;
   }
?>