<?
//
// $Id$
//
function KickOff
   (
   $mode = ""
   )
   {
   ?>
   <p>Your KEYclick Boarding Pass is invalid.&nbsp; Possible reasons include:</p>
   <ul>
      <li><p>Your KEYclick session has been idle for more than 30 minutes;</p></li>
      <li><p>This is not the computer you used to log into KEYclick (ie, your IP address has changed).</p></li>
   </ul>
   <p><b><a href=<? echo HomePageUrl(); ?>>Click here to log back into KEYclick.</a></b></p>
   <?
   }
?>