<?
//
// $Id$ */
//
function ReadDump_RODFOLUP0
   (
   $year_num,
   $month_num,
   $day_num,
   $bpn,
   $mode = ""
   )
{
$statement_array = array();
$statement_array[$i = 0] = "drop table if exists " . $mode . "recent_donation";
$statement_array[++$i] = "drop table if exists " . $mode . "resident_follow_up";
$statement_array[++$i] = "CREATE TABLE " . $mode . "recent_donation SELECT id FROM " . $mode . "donation WHERE date > '$year_num-$month_num-$day_num'";
$statement_array[++$i] = "CREATE TABLE " . $mode . "resident_follow_up SELECT " . $mode . "resident.* FROM " . $mode . "resident LEFT JOIN " . $mode . "recent_donation ON " . $mode . "resident.id=" . $mode . "recent_donation.id WHERE " . $mode . "recent_donation.id IS NULL";
$statement_array[++$i] = "drop table " . $mode . "recent_donation";
//
$num_statements = count($statement_array);
//
// Execute each statement in the statement array.
//
for ($i = 0; $i < $num_statements; $i++)
   {
   mysql_query($statement_array[$i]) or die("Query [$statement_array[$i]] failed with error: " . mysql_error());
   }
}
?>