<?
//
// $Id$ */
//
function ReadDump_RODFOLUP0
   (
   $db_link,
   $year_num,
   $month_num,
   $day_num,
   $bpn,
   $agency,
   $mode = ""
   )
{
$statement_array = array();
$statement_array[$i = 0] = "drop table if exists " . $mode . "recent_donation";
$statement_array[++$i] = "drop table if exists " . $mode . "resident_follow_up";
$statement_array[++$i] = "CREATE TABLE " . $mode . "recent_donation SELECT id FROM " . $mode . "donation WHERE date > '$year_num-$month_num-$day_num'";
$statement_array[++$i] = "CREATE TABLE " . $mode . "resident_follow_up"
. " SELECT " . $mode . "resident_base.id"
  . " , resident_base.name"
  . " , concat(house_num,' ',street.name) as address1"
  . " , city.name as city"
  . " , state.abbreviation as state"
. " FROM " . $mode . "resident_base"
  . " join street on (street.id=resident_base.street_id)"
  . " join city on (city.id=street.city_id)"
  . " join state on (state.id=city.state_id)"
  . " LEFT JOIN " . $mode . "recent_donation on (recent_donation.id=resident_base.id)"
. " WHERE " . $mode . "recent_donation.id IS NULL"
  . " and agency='$agency'";
$statement_array[++$i] = "drop table " . $mode . "recent_donation";
//
$num_statements = count($statement_array);
//
// Execute each statement in the statement array.
//
for ($i = 0; $i < $num_statements; $i++)
   {
   $db_link->query($statement_array[$i]) or die("Query [$statement_array[$i]] failed with error: " . mysqli_error($db_link));
   }
}
?>