<?
//
// $Id$
//
function RoleEmailAddress
   (
   $role = "",
   $mode = "",
   $agency = ""
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $email_addr = "";
   if ($role == "") $role = "sysadmin";
   //
   $result = mysql_query
      (
      "select email_addr from " . $mode . "authority "
      .  "   where role='$role' "
      .  "      and agency='$agency' "
      .  "   limit 1"
      )
      or die("RoleEmailAddress query failed with error:  " . mysql_error());
   //
   if (mysql_num_rows($result)) extract(mysql_fetch_array($result));
   //
   error_reporting($saved_error_level);
   return $email_addr;
   }
?>