<?php
//
// $Id$
//
function ViewQuery
  (
  $db_link,
  $bpn,
  $sql_query,
  $lang,
  $server,
  $zero_rows,
  $goto,
  $table_border,
  $cell_padding,
  $max_text_field_display_len,
  $mode = "",
  $disp_mode = ""
  )
  {
  $result = $db_link->query($sql_query) or die("Query $sql_query returned '" . mysqli_error($db_link) . "'");
  if(($num_rows = @mysqli_num_rows($result)) < 1)
    {
    echo "<p>$zero_rows</p>";
    }
  else
    {
    while (($field = mysqli_fetch_field($result)) === TRUE) // get the list of fields properties
      {
      $fields_meta[] = $field;
      }
    if (empty($disp_mode))
      {
      $disp_mode = 'urdr11110'; // see the "PMA_setDisplayMode()" function in libraries/display_tbl.lib.php3
      }
    PMA_displayTable
      (
      $result,
      $disp_mode,
      $fields_meta,
      count($fields_meta),
      $bpn,
      $sql_query,
      $max_text_field_display_len,
      $mode,
      $table_border,
      $cell_padding
      );
    mysqli_free_result($result);
  }
echo "\n\n";
}
?>