<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$phase = $phase;
$id = $id;
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_connectselectdb.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
?>
<html>

<head>
<title>KEYclick - Modify or remove resident record</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              <a href="<? echo HomePageUrl(); ?>">KEYCLICK SYSTEM</a></h6>
           <h1 align="center">Modify or remove resident record</h1>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced("eye-candy",1); ?>
        </td></tr></table>
        <hr>
        <?
        if (ConnectSelectDb("localhost","kalipso",Password(),"keyclick") != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>KEYclick's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
           </blockquote>            
           </b>
           <?
           }
        else
           {
           if ($id != "")
              {
              $result = mysql_query
                 (
                 "select name "
                 .  ", address1 "
                 .  ", city "
                 .  ", state "
                 .  ", zip "
                 .  "from resident "
                 .  "where id='$id' "
                 )
                 or die("Query failed with error: " . mysql_error());
              $num_rows = mysql_num_rows($result);
              if ($num_rows)
                 {
                 extract(mysql_fetch_array($result));
                 echo "<form action=" . $mode . "form-act-singly.phtml method=post>\n"
                    . "<blockquote>\n"
                    . "   <table>\n"
                    . "      <tr><td align=right><b>Resident ID:</b></td><td colspan=2><b>$id</b></td></tr>\n"
                    . "      <tr><td align=right>Name:</td><td colspan=2><input type=text name=name value=\"$name\" size=60 maxlength=60></td></tr>\n"
                    . "      <tr><td align=right>Address:</td><td colspan=2><input type=text name=address1 value=\"$address1\" size=60 maxlength=60></td></tr>\n"
                    . "      <tr><td align=right>City:</td><td colspan=2><input type=text name=city value=\"$city\" size=40 maxlength=40></td></tr>\n"
                    . "      <tr><td align=right>State:</td><td colspan=2><input type=text name=state value=\"$state\" size=2 maxlength=2></td></tr>\n"
                    . "      <tr><td align=right>Zip code:</td><td colspan=2><input type=text name=zip value=\"$zip\" size=10 maxlength=10></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td align=right valign=top>Action:</td>\n"
                    . "         <td colspan=2>\n"
                    . "            <input type=radio name=action value=update checked>Update it<br>\n"
                    . "            <input type=radio name=action value=delete>Delete it\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "      <tr><td colspan=3><hr></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td colspan=3 align=center>\n"
                    . "            Next Resident ID to modify/remove (optional):\n"
                    . "            <input type=text name=id value=\"\" maxlength=5 size=5>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "      <tr><td colspan=3><hr></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td colspan=3>\n"
                    . "            <table width=100%>\n"
                    . "               <tr>\n"
                    . "                  <td align=center><input type=submit name=go value=Save></td>\n"
                    . "                  <td align=center><input type=submit name=cancel value=Cancel></td>\n"
                    . "               </tr>\n"
                    . "            </table>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "   </table>\n"
                    . "</blockquote>\n"
                    . "</form>\n";
                 }
              else
                 {
                 ?>
                 <p><b>No such Resident ID found.</b></p>
                 <center>
                    <form action=<? echo $mode; ?>form-act-singly.phtml method=post>
                       Edit and retry:
                       <input type=text name=id maxlength=5 size=5 value=<? echo $id; ?>>
                       <input type=submit value="Go!">&nbsp; &nbsp;<input type=submit name=cancel value=Cancel>
                    </form>
                 </center>
                 <?
                 }
              } // non-null $id
           } // database up
        ?>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>

