<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_password.phtml");
require_once("f_connectselectdb.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
//
$connected = (ConnectSelectDb("localhost","kalipso",Password(),"keyclick") == "TRUE");
?>
<html>

<head><title>KEYclick - Export ROD</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced("eye-candy",1); ?>
        </td><td>
           <h6 align="center">
              <a href="<? echo HomePageUrl(); ?>">KEYCLICK SYSTEM</a></h6>
           <h1 align="center">Export ROD</h1>
        </td></tr></table>
        <hr>
        <br>
        <?
        if ($connected != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>KEYclick's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
           </blockquote>            
           </b>
           <?
           }
        else
           {
           //
           $agency = BeValidBoardingPass($bpn,$mode);
           if ($agency == "")
              {
              KickOff($mode);
              }
           else
              {
              ?>
              <p>Because of its size, the ROD must be downloaded as three separate ZIP files.&nbsp; KEYclick recommends that you deliver
                 the ZIP files, unaltered, to Corporate Marketing Inc. via email or floppy disk.</p>
              <p><b>Please <u>WAIT PATIENTLY</u> after clicking a button.&nbsp; In each case, it will take a while for the
                 server to crunch the data before starting the download.</b></p>
              <blockquote>
                 <form action=<? echo $mode; ?>export.phtml method=post>
                     <input type=hidden name=bpn value="<? echo $bpn; ?>">
                     <input type=hidden name="filename" value="resident-part-1-of-3">
                     <input type=hidden name="whole_query" value="select unk1,subdrive,id,unk2,salutation,name,address1,unk3,city,state,zip,unk4,unk5,unk6,unk7,unk8 from <? echo $mode; ?>resident where agency = '<? echo $agency; ?>' limit 0,13500">
                     <input type=submit value="Download ROD Part 1">
                 </form>
                 <form action=<? echo $mode; ?>export.phtml method=post>
                     <input type=hidden name=bpn value="<? echo $bpn; ?>">
                     <input type=hidden name="filename" value="resident-part-2-of-3">
                     <input type=hidden name="whole_query" value="select unk1,subdrive,id,unk2,salutation,name,address1,unk3,city,state,zip,unk4,unk5,unk6,unk7,unk8 from <? echo $mode; ?>resident where agency = '<? echo $agency; ?>' limit 13500,13500">
                     <input type=submit value="Download ROD Part 2">
                 </form>
                 <form action=<? echo $mode; ?>export.phtml method=post>
                     <input type=hidden name=bpn value="<? echo $bpn; ?>">
                     <input type=hidden name="filename" value="resident-part-3-of-3">
                     <input type=hidden name="whole_query" value="select unk1,subdrive,id,unk2,salutation,name,address1,unk3,city,state,zip,unk4,unk5,unk6,unk7,unk8 from <? echo $mode; ?>resident where agency = '<? echo $agency; ?>' limit 27000,13500">
                     <input type=submit value="Download ROD Part 3">
                 </form>
              </blockquote>
              <?
              }
           }
        ?>
        <br>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
      </td>
    </tr>
  </table>
</body>

</html>
