<?
//
// $Id$
//
require_once("f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$save = $save;
$id = $id;
//
if ($mode) error_reporting(E_ALL);
//
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
require_once("f_connectselectdb.phtml");
require_once("f_password.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_formattednoteappendage.phtml");
require_once("f_emailaddrofbpn.phtml");
?>
<html>

<head>
<title>KEYclick - Modify or remove resident record</title>
</head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <table><tr><td>
           <h6 align="center">
              <a href=<? echo HomePageUrl(); ?>>KEYCLICK SYSTEM</a></h6>
           <h1 align="center">Modify or remove resident record</h1>
        </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
           <? PutLibPhotoRandomPlaced("eye-candy",1); ?>
        </td></tr></table>
        <hr>
        <br>
        <?
        if (ConnectSelectDb("localhost","kalipso",Password(),"keyclick") != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>KEYclick's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
           </blockquote>            
           </b>
           <?
           }
        else
           {
           if (($agency = BeValidBoardingPass($bpn,$mode)) == "")
              {
              KickOff($mode);
              }
           else
           {
           //
           // Database is up.
           //
           $feedback_column_width_percentage = 25;
           echo "<table width=100%><tr>"
              . "<td width=$feedback_column_width_percentage% valign=top bgcolor=#F7F7F7 cellspacing=10>"
              . "<p><b><u>Previous operation</u></b></p>\n";
           if ($save)
              {
              //
              // User indicated that data should be saved.  Validate parameters.
              //
              echo "<small>\n";
              //
              if (($action == "update") or ($action == "delete"))
                 {
                 $result = mysql_query
                    (
                    "select name as old_name "
                    .  " , address1 as old_address1 "
                    .  " , city as old_city "
                    .  " , state as old_state "
                    .  " , zip as old_zip "
                    .  " from " . $mode . "resident "
                    .  " where id=$id_to_save "
                    )
                    or die("Select failed with error: " . mysql_error());
                 //
                 extract(mysql_fetch_array($result));
                 }
              if ($action == "update")
                 {
                 if (
                       ($name != "")
                    and
                       ($address1 != "")
                    and
                       ($city != "")
                    and
                       ($state != "")
                    and
                       ($zip != "")
                    )
                 // then
                    {
                    $result = mysql_query
                       (
                       "update " . $mode . "resident "
                       .  "set name='" . addslashes($name) . "' "
                       .  "   , address1='" . addslashes($address1) . "' "
                       .  "   , city='" . addslashes($city) . "' "
                       .  "   , state='" . addslashes($state) . "' "
                       .  "   , zip='" . addslashes($zip) . "' "
                       .  "where id=$id_to_save "
                       .  "limit 1 "
                       )
                       or die("Update failed with error: " . mysql_error());
                    //
                    $result = mysql_query
                       (
                       "insert into " . $mode . "resident_journal "
                       .  "set name='" . addslashes($old_name) . "' "
                       .  "   , address1='" . addslashes($old_address1) . "' "
                       .  "   , city='" . addslashes($old_city) . "' "
                       .  "   , state='" . addslashes($old_state) . "' "
                       .  "   , zip='" . addslashes($old_zip) . "' "
                       .  "   , id=$id_to_save "
                       .  "   , op='UPDATE' "
                       .  "   , user_email_addr='" . EmailAddrOfBpn($bpn,$mode) . "' "
                       )
                       or die("Journal entry failed with error: " . mysql_error());
                    //
                    echo "<p><b>SUCCEEDED</b></p>\n"
                       . "<small><dl>\n"
                       . "<dt>Resident ID:</dt><dd>$id_to_save</dd>\n"
                       . "<dt>Name:</dt><dd>$name</dd>\n"
                       . "<dt>Address:</dt><dd>$address1</dd>\n"
                       . "<dt>City:</dt><dd>$city</dd>\n"
                       . "<dt>State:</dt><dd>$state</dd>\n"
                       . "<dt>Zip:</dt><dd>$zip</dd>\n"
                       . "</dl></small>\n";
                    }
                 else
                    {
                    echo "<p><b><u>FAILED</u></b></p>\n"
                       . "<p><b>One or more fields were missing.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the "
                       . "problem.</b></p>\n";
                    }
                 }
              elseif ($action == "delete")
                 {
                 $result = mysql_query
                    (
                    "delete from " . $mode . "resident "
                    .  "where id=$id_to_save "
                    .  "limit 1"
                    )
                    or die("Delete failed with error: " . mysql_error());
                 //
                 $result = mysql_query
                    (
                    "insert into " . $mode . "resident_journal "
                    .  "set name='" . addslashes($old_name) . "' "
                    .  "   , address1='" . addslashes($old_address1) . "' "
                    .  "   , city='" . addslashes($old_city) . "' "
                    .  "   , state='" . addslashes($old_state) . "' "
                    .  "   , zip='" . addslashes($old_zip) . "' "
                    .  "   , id=$id_to_save "
                    .  "   , op='DELETE' "
                    .  "   , user_email_addr='" . EmailAddrOfBpn($bpn,$mode) . "' "
                    )
                    or die("Journal entry failed with error: " . mysql_error());
                 //
                 echo "<p><b>SUCCEEDED</b></p>\n"
                    . "<small>Resident ID $id_to_save has been deleted.</small>\n";
                 }
              else
                 {
                 echo "<p><b>FAILED</b></p>\n"
                    . "<p><b>Missing or unknown <u>action</u>.</p>\n";
                 }
              //
              echo "</small>\n";
              //
              $name = $address1 = $city = $state = $zip = "";
              //
              }
           else
              {
              echo "<p>None</p>\n";
              }
           //
           echo "</td><td width=5%>&nbsp;</td><td valign=top>\n";
           //
           if ($id != "")
              {
              //
              // Lookup record with specified ID.
              //
              $result = mysql_query
                 (
                 "select name "
                 .  ", address1 "
                 .  ", city "
                 .  ", state "
                 .  ", zip "
                 .  "from " . $mode . "resident "
                 .  "where id='$id' "
                 )
                 or die("Query failed with error: " . mysql_error());
              $num_rows = mysql_num_rows($result);
              if ($num_rows)
                 {
                 extract(mysql_fetch_array($result));
                 echo "<p><b><u>Current operation:</u></b></p>\n"
                    . "<form action=" . $mode . "form-act-singly.phtml method=post>\n"
                    . "   <input type=hidden name=bpn value=$bpn>\n"
                    . "   <input type=hidden name=id_to_save value=$id>\n"
                    . "<blockquote>\n"
                    . "   <table>\n"
                    . "      <tr><td align=right><b>Resident ID:</b></td><td colspan=2><b>$id</b></td></tr>\n"
                    . "      <tr><td align=right>Name:</td><td colspan=2><input type=text name=name value=\"$name\" size=50 maxlength=50></td></tr>\n"
                    . "      <tr><td align=right>Address:</td><td colspan=2><input type=text name=address1 value=\"$address1\" size=50 maxlength=50></td></tr>\n"
                    . "      <tr><td align=right>City:</td><td colspan=2><input type=text name=city value=\"$city\" size=35 maxlength=35></td></tr>\n"
                    . "      <tr><td align=right>State:</td><td colspan=2><input type=text name=state value=\"$state\" size=2 maxlength=2></td></tr>\n"
                    . "      <tr><td align=right>Zip code:</td><td colspan=2><input type=text name=zip value=\"$zip\" size=10 maxlength=10></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td align=right valign=top>Action:</td>\n"
                    . "         <td colspan=2>\n"
                    . "            <input type=radio name=action value=update checked>Update<br>\n"
                    . "            <input type=radio name=action value=delete>Delete\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "      <tr><td colspan=3><hr></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td colspan=3 align=center>\n"
                    . "            Next Resident ID to modify/remove (optional):\n"
                    . "            <input type=text name=id value=\"\" maxlength=5 size=5>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "      <tr><td colspan=3><hr></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td colspan=3>\n"
                    . "            <table width=100%>\n"
                    . "               <tr>\n"
                    . "                  <td align=center><input type=submit name=save value=Save></td>\n"
                    . "                  <td align=center><input type=submit name=cancel value=Cancel></td>\n"
                    . "               </tr>\n"
                    . "            </table>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "   </table>\n"
                    . "</blockquote>\n"
                    . "</form>\n";
                 }
              else
                 {
                 ?>
                 <p><b>No such Resident ID found.</b></p>
                 <blockquote>
                    <form action=<? echo $mode; ?>form-act-singly.phtml method=post>
                       Edit and retry:
                       <input type=hidden name=bpn value=<? echo $bpn; ?>>
                       <input type=text name=id maxlength=5 size=5 value=<? echo $id; ?>>
                       <input type=submit value="Go!">
                    </form>
                 </blockquote>
                 <?
                 }
              } // non-null $id
           else
              {
              //
              // No ID specified.
              //
              echo "<p><b>No Resident ID specified</b></p>\n"
                 . "<blockquote>\n"
                 . "   <form action=" . $mode . "form-act-singly.phtml method=post>\n"
                 . "      <input type=hidden name=bpn value=$bpn>\n"
                 . "      Specify a Resident ID:\n"
                 . "      <input type=text name=id maxlength=5 size=5 value=$id>\n"
                 . "      <input type=submit value=\"Go!\"><br>\n"
                 . "      <br>\n"
                 . "      -- or --<br>\n"
                 . "      <br>\n"
                 . "      <a href=" . $mode . "main.phtml?bpn=$bpn>Return to main KEYclick page.</a>\n"
                 . "   </form>\n"
                 . "</blockquote>\n";
              }
           //
           echo "</td></tr></table>\n";
           //
           } // BeValidBoardingPass
           } // database up
        ?>
        <br>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>
