<?php
//
// $Id$
//
//
// Emulate register_globals on
if (!ini_get('register_globals'))
  {
  $superglobals = array($_SERVER,$_ENV,$_FILES,$_COOKIE,$_POST,$_GET);
  if (isset($_SESSION))
    {
    array_unshift($superglobals, $_SESSION);
    }
  foreach ($superglobals as $superglobal)
    {
    extract($superglobal, EXTR_SKIP);
    }
  }
require_once("f_runmode.phtml");
$mode = "";
//
// Assign incoming arguments to themselves to prevent 'uninitialized variable' warnings later.
//
$bpn = $bpn;
$add_and_cancel = $add_and_cancel;
$add_and_repeat = $add_and_repeat;
$cancel = $cancel;
//
if (RunMode($PHP_SELF)) error_reporting(E_ALL);
//
require_once("f_homepageurl.phtml");
require_once("f_bodyopen.phtml");
require_once("f_connectselectdbinstanceunpublished.phtml");
require_once("f_roleemailaddress.phtml");
require_once("f_bevalidboardingpass.phtml");
require_once("f_kickoff.phtml");
require_once("f_formattednoteappendage.phtml");
require_once("f_emailaddrofbpn.phtml");
require_once("f_streetselectionlist.phtml");
?>
<html>

<head>
<title>KEYclick - Add resident</title>
</head>

<?php BodyOpen("CurrentOperation.last_name"); ?>

<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
        <h6 align="center"><a href=<? echo HomePageUrl(); ?>>KEYCLICK SYSTEM</a></h6>
        <h1 align="center">Add resident</h1>
        <hr>
        <br>
        <?php
        if (ConnectSelectDbInstanceUNPUBLISHED($db_link) != "TRUE")
           {
           ?>
           <h2><i>Sorry...</i></h2>
           <b>
           <blockquote>
              <? echo "<p>KEYclick's database is temporarily offline.&nbsp; Please try again later.</p>"; ?>
           </blockquote>            
           </b>
           <?php
           }
        else
           {
           //
           // Database is up.
           //
           //
           $agency = BeValidBoardingPass($db_link,$bpn,$mode);
           if ($agency == "")
              {
              KickOff($mode);
              }
           else
              {
              $feedback_column_width_percentage = 25;
              echo "<table width=100%><tr>"
                 . "<td width=$feedback_column_width_percentage% valign=top bgcolor=#F7F7F7 cellspacing=10>"
                 . "<p><b><u>Previous operation</u></b></p>\n";
              if (($add_and_repeat) or ($add_and_cancel))
                 {
                 //
                 // User indicated that data should be saved.  Validate parameters.
                 //
                 echo "<small>\n";
                 //
                 if (
                       ($last_name != "")
                    and
                       ($street_id != "")
                    )
                 // then
                    {
                    if ($apt_num) $street_num = "$street_num-$apt_num";
                    //
                    $name = strtoupper("$last_name $name_detail");
                    $street_num = strtoupper("$street_num");
                    //
                    extract(mysqli_fetch_array($db_link->query("select max(id)+1 as new_id from " . $mode . "resident_base")));
                    //
                    $result = $db_link->query
                       (
                       "insert into " . $mode . "resident_base"
                       . " set name = '" . addslashes($name) . "'"
                       . " , house_num = '" . addslashes($street_num) . "'"
                       . " , street_id = '" . addslashes($street_id) . "'"
                       . " , id = '$new_id'"
                       . " , agency = '$agency'"
                       )
                       or die("Cardinal insert failed with error: " . mysqli_error($db_link));
                    //
                    extract
                       (
                       mysqli_fetch_array
                          (
                          $db_link->query
                             (
                             "select street.name as street_name"
                             . " , city.name as city_name"
                             . " , state.abbreviation as state_abbreviation"
                             . " from street"
                               . " join city on (city.id=street.city_id)"
                               . " join state on (state.id=city.state_id)"
                             . " where street.id = '$street_id'"
                             )
                          )
                       );
                    $address1 = "$street_num $street_name";
                    $result = $db_link->query
                       (
                       "insert into " . $mode . "resident_journal "
                       .  "set name='" . addslashes($name) . "' "
                       .  "   , address1='" . $address1 . "' "
                       .  "   , city='" . addslashes($city_name) . "' "
                       .  "   , state='" . addslashes($state_abbreviation) . "' "
                       .  "   , id=$new_id "
                       .  "   , op='INSERT' "
                       .  "   , user_email_addr='" . EmailAddrOfBpn($db_link,$bpn,$mode) . "' "
                       )
                       or die("Journal entry failed with error: " . mysqli_error($db_link));
                    //
                    echo "<p><b>SUCCEEDED</b></p>\n"
                       . "<small><dl>\n"
                       . "<dt>Resident ID:</dt><dd>$new_id</dd>\n"
                       . "<dt>Name:</dt><dd>$name</dd>\n"
                       . "<dt>Address:</dt><dd>$address1</dd>\n"
                       . "<dt>City:</dt><dd>$city_name</dd>\n"
                       . "<dt>State:</dt><dd>$state_abbreviation</dd>\n"
                       . "</dl></small>\n"
                       . "<u>Optional</u>: For this record, log:\n"
                       . "<table>\n"
                       . "   <tr><td><small><li>&nbsp;</small></td><td><small><a href=" . $mode . "form-add-donation.phtml?bpn=$bpn&cross_id=$new_id>NEW donation</a></small></td></tr>\n"
                       . "   <tr><td><small><li>&nbsp;</small></td><td><small><a href=" . $mode . "form-add-donation-old.phtml?bpn=$bpn&cross_id=$new_id>OLD donation</a></small></td></tr>\n"
                       . "</table>\n";
                    }
                 else
                    {
                    echo "<p><b>FAILED</b></p>\n"
                       . "<p><b>One or more fields were missing or invalid.&nbsp; Press your browser's [<-&nbsp;BACK] button to fix the "
                       . "problem.</b></p>\n";
                    }
                 //
                 echo "</small>\n";
                 //
                 $new_id = $last_name = $name_detail = $name = $street_num = $address1 = $apt_num = $city = $state =
                    $zip = "";
                 //
                 }
              else
                 {
                 echo "<p>None</p>\n";
                 }
              //
              echo "</td><td width=5%>&nbsp;</td><td valign=top>\n";
              //
              if ((!$add_and_cancel) and (!$cancel))
                 {
                 echo "<p><b><u>Current operation:</u></b></p>\n"
                    . "<form name=CurrentOperation action=" . $mode . "form-add-resident.phtml method=post>\n"
                    . "   <input type=hidden name=bpn value=$bpn>\n"
                    . "   <table>\n"
                    . "      <tr><td align=right>Last name:</td><td colspan=2><input type=text name=last_name size=20 maxlength=20></td></tr>\n"
                    . "      <tr><td align=right>First/other name(s):</td><td colspan=2><input type=text name=name_detail size=30 maxlength=30></td></tr>\n"
                    . "      <tr><td align=right>House/building #:</td><td colspan=2><input type=text name=street_num size=6 maxlength=10></td></tr>\n"
                    . "      <tr><td align=right>Street, City, State:</td><td colspan=2>";
                 StreetSelectionList($db_link,$mode);
                 echo "</td></tr>\n"
                    . "      <tr><td align=right>Apt #:</td><td colspan=2><input type=text name=apt_num size=4 maxlength=6></td></tr>\n"
                    . "      <tr>\n"
                    . "         <td colspan=2>\n"
                    . "            <table width=100%>\n"
                    . "               <tr>\n"
                    . "                  <td align=center><input type=submit name=add_and_repeat value=\"Add and Repeat\"></td>\n"
                    . "                  <td align=center><input type=submit name=add_and_cancel value=\"Add and Stop\"></td>\n"
                    . "                  <td align=center><input type=submit name=cancel value=Cancel></td>\n"
                    . "               </tr>\n"
                    . "            </table>\n"
                    . "         </td>\n"
                    . "      </tr>\n"
                    . "   </table>\n"
                    . "</form>\n";
                 }
              else
                 {
                 echo "<p><b><a href=\"javascript:close();\">Go to <b>Main KEYclick</b> page.</a></b></p>\n";
                 }
              echo "</td></tr></table>\n";
              //
              } // BeValidBoardingPass
           } // database up
        ?>
        <br>
        <p><small><small><em><pre>$Id$</pre></em></small></small>
       </td>
    </tr>
  </table>
</body>

</html>
