<?
//
// $Id$
//
require_once("f_homepageurl.phtml");
require_once("f_putlibphotorandomplaced.phtml");
require_once("f_bodyopen.phtml");
?>
<html>

<head><title>KEYclick - What's New</title></head>

<? BodyOpen(); ?>
<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">
   <tr>
      <td>
           <h6 align="center"><a href="<? echo HomePageUrl(); ?>">KEYCLICK SYSTEM</a></h6>
           <h1 align="center">What's New</h1>
        <hr>
        <? PutLibPhotoRandomPlaced("eye-candy",1,"right"); ?>
        <p><b>2002-04-19:&nbsp; </b>Revised the Add action page to accept house/building number, street name, and apartment
           number as distinct fields.&nbsp; This will allow KEYclick to enforce a standard notation.</p>
        <p><b>2002-04-11:&nbsp; </b>Added journaling.  Now all changes to the ROD will be associated with a user, and
           can be easily reversed.</p>
        <p><b>2002-04-09:&nbsp; </b>Implemented privacy/security mechanism (email authentication) and the Export
           capability.</p>
        <p><b>2002-03-12:&nbsp; </b>Implemented Add Resident capability.</p>
        <p><b>2002-03-11:&nbsp; </b>Went live with Modify/Remove Resident capability.</p>
        <p><b>2002-03-11:&nbsp; </b>Began script development.</p>
        <hr>
        <p><small><small><em><pre>$Id$</pre></em></small></small></center></td>
    </tr>
  </table>
</body>

</html>

